### ISSUE TITLE
Keystrokes in the browser should not be logged

### ISSUE THREAD

**Issue by m133225** [se-edu/addressbook-level4#10]
Currently they are being logged as `KeyBindingEvent`s.
This is applicable if the user has to enter username/password into the browser to login to GitHub.

**Comment by yl-coder** [comment]
Fixed via commit [386dffdf2ad3453c7ac73cb7d93694c270f4ebae](https://github.com/se-edu/addressbook-level4/commit/386dffdf2ad3453c7ac73cb7d93694c270f4ebae)
