### ISSUE TITLE
ConfigUtilTest fails : AssertionError not thrown as expected

### ISSUE THREAD

**Issue by okkhoy** [se-edu/addressbook-level4#105]
- `save_null_file_assertionFailure` 
- `read_null_assertionFailure`
- `save_nullConfig_assertionFailure`

Tests fail with NullPointerException

They expect `AssertionError`

**Comment by damithc** [comment]
AssertionError is thrown only when assertions are enabled. However, JUnit is supposed to enable assertions by default.

**Comment by damithc** [comment]
Try this:
![image](https://cloud.githubusercontent.com/assets/1673303/18826875/41036a24-8402-11e6-9417-7e519699edec.png)

**Comment by okkhoy** [comment]
I enabled the flags as above; still gives me NPE.

**Comment by damithc** [comment]
As discussed, most likely the setting is not applied to existing run configurations. We can update our dev guide to ask devs to check the flag during setting up.
