### ISSUE TITLE
XMLUtilTest

### ISSUE THREAD

**Issue by okkhoy** [se-edu/addressbook-level4#107]
- `getDataFromFile_nullClass_AssertionError` (fails with `IllegalArgumentException`)
- `getDataFromFile_nullFile_AssertionError` (fails with `NullPointerException`)
- `saveDataToFile_nullClass_AssertionError` (fails with `NullPointerException`)
- `saveDataToFile_nullFile_AssertionError` (fails with `NullPointerException`)

They all expect `AssertionError`

**Comment by damithc** [comment]
Same as #105
