### ISSUE TITLE
JsonUserPrefStorageTest

### ISSUE THREAD

**Issue by okkhoy** [se-edu/addressbook-level4#108]
- `savePrefs_nullPrefs_assertionFailure` test fails with no reason specified
- `saveUserPrefs_nullFilePath_assertionFailure` (fails with `NullPointerException`)
- `readUserPrefs_nullFilePath_assertionFailure` (fails with `NullPointerException`)

They all expect `AssertionError`

**Comment by damithc** [comment]
Same as #105
