### ISSUE TITLE
Load UserGuide in the help window.

### ISSUE THREAD

**Issue by m133225** [se-edu/addressbook-level4#11]
Currently outdated. Things like hotkey to resize application should be removed.

**Comment by damithc** [comment]
Perhaps we simply load the `doc/UserGuide.md` ? Students may not have time to write a user guide in html.

**Comment by damithc** [comment]
@lejolly can do this one?

**Comment by lejolly** [comment]
is the only shortcut we have now the `F1` key for help?

**Comment by damithc** [comment]
Yes, that and the `help` command.

**Comment by damithc** [comment]
Yes, can remove the existing html file.
