### ISSUE TITLE
Log file recreated every time

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#126]
Problem 1. Log file is not used when running from IDE (log file has only 2 lines)
Problem 2. When running from jar, log file is recreated every time I run the app.

**Comment by damithc** [comment]
@m133225 can fix this one?

**Comment by m133225** [comment]
Does this mean that the old log messages are being overwritten?

**Comment by damithc** [comment]
Yes.

**Comment by m133225** [comment]
Can't seem to reproduce 1). Maybe deleting the possibly old config file will help.

**Comment by damithc** [comment]
When running from IDE, this is all I see in the log file.
```
Sep 28, 2016 4:15:25 PM seedu.address.storage.XmlAddressBookStorage readAddressBook
INFO: AddressBook file .\src\test\data\XmlAddressBookStorageTest\NonExistentFile.xml not found
```

**Comment by damithc** [comment]
But problem 2 is still there. Every time I start the app (whether it is from IDE or jar file), the file is wiped clean.

**Comment by damithc** [comment]
Confirmed from home comp. If you cannot reproduce this, it could be a Windows-only thing.

**Comment by damithc** [comment]
@lejolly can you help to check this on your Mac?

**Comment by lejolly** [comment]
1. doesn't happen to me
2. does
