### ISSUE TITLE
User can undo previous actions

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#135]
... so that user can recover from mistakes.

**Comment by m133225** [comment]
- Limited to actions on mutable objects

**Comment by damithc** [comment]
This seems relevant https://github.com/TomasMikula/UndoFX

**Comment by YijinL** [comment]
It uses [ReactFX](https://github.com/TomasMikula/ReactFX). I 101% support the functional reactive paradigm but I think it falls too far outside 2103 scope.

**Comment by damithc** [comment]
I see. Let's not use it in that case.
