### ISSUE TITLE
Let commands have access to Storage

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#158]
Some future commands (e.g. change save location) might need access to storage component.

**Comment by Zhiyuan-Amos** [comment]
Prerequisite: #632. Refer to #212 on how to resolve this issue.

**Comment by yamgent** [comment]
You cannot implement #632 without implementing this first.

**Comment by Zhiyuan-Amos** [comment]
LOL you're right. Thanks for correcting my mistake. We should close this issue right? Since letting commands have access to Storage only makes sense when we have a dedicated command that sets the Storage location.

**Comment by yamgent** [comment]
Yeah, we should update the other issue to mention that it will be implemented by letting commands having access to Storage.
