### ISSUE TITLE
Implement ListAllCommand

### ISSUE THREAD

**Issue by yl-coder** [se-edu/addressbook-level4#16]
As per title

**Comment by lejolly** [comment]
@m133225 @yl-coder is there an event to trigger the updating of the GUI without updating the model (or if it's not possible, at least without updating the local file)?

**Comment by yl-coder** [comment]
The GUI is tied to the model. There is no event to update the GUI. The list view is tied to the list that it is controlling. We will need to pass a filteredList to the Listview. And the ListAllCommand will simply set the predicate to show all person. And the SearchCommand will set a predicate to the filteredList show a subset of persons.

Currently, the FilteredList is not implemented yet. We need to change the list used in PersonListPanel to use FilteredList instead of ObservableList.

On 24 Aug 2016, at 6:26 PM, Joshua Lee <notifications@github.com<mailto:notifications@github.com>> wrote:


@m133225<https://github.com/m133225> @yl-coder<https://github.com/yl-coder> is there an event to trigger the updating of the GUI without updating the model (or if it's not possible, at least without updating the local file)?

**Comment by lejolly** [comment]
wait, so are we adding back what was taken out in df1119c3e1f88c3688639e794741f5181234415a? or doing a simpler version of what was taken out?

and by `SearchCommand` do you mean `FindPersonsByWordsInNameCommand`?
