### ISSUE TITLE
Include test code in coverage analysis

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#161]
Including test code will help us find missing @Test tags and dead test code.

**Comment by damithc** [comment]
Contrary to expectations, it dropped the coverage level because methods testing exceptions don't seem to be captured as covered. :-p We may have to revert this one :-(

**Comment by m133225** [comment]
Thought that was the case at first that's why I didn't ask for a review yet 😛 Shall we just create another issue instead?

**Comment by damithc** [comment]
Yes, can be done as a new issue, but it's going to be just a reversal of this PR. Apparently, it is a known issue with eclemma and the common advice is to omit test code from coverage analysis :-p
