### ISSUE TITLE
Discussion: Prepare Methods in Parser class in violation of SRP?

### ISSUE THREAD

**Issue by mauris** [se-edu/addressbook-level4#169]
While reviewing code, I find that the `Parser` class in Level 4 has prepare methods for each command. It feels like this is a violation of SRP and does not follow open-close principle. Adding new commands would require addition of such methods. 

If we were to refactor this, would following the Factory pattern - by having one concrete factory for each concrete command - be better?

**Comment by damithc** [comment]
Yes, that's a good observation @mauris 
#137 is supposed to fix that problem.

**Comment by mauris** [comment]
Right, couldn't find the corresponding issue. Thank you Prof @damithc!
