### ISSUE TITLE
Gui tests failing because 'can't find stage'

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#170]
Some students reported GUI tests failing with this error although some team members were able to run the tests with the same code.
`WARNING: Can't find stage Test App, Therefore, aborting focusing`

A resource/timing issue? How to resolve/workaround?

**Comment by damithc** [comment]
@yl-coder any ideas?

**Comment by damithc** [comment]
A response from one of the students 
```
I solved it by making the command box auto-focus: add commandTextField.requestFocus(); 
at the end of method addToPlaceholder() in CommandBox.java. It should work!

But my group's gui contains some buttons and the guiRobot doesn't click on the exact location. 
So we still cannot pass the junit test in eclipse anyway :(
```

**Comment by shixiyue** [comment]
Sorry I didn't state it clearly in my reply. My reply is regarding to PEH XIAN BIN, EUGENE's post:

> it seems that if we shift the position of commandBox, the guiRobot doesn't clicks on the commandBox position and clicks somewhere else. However our headless test using gradlew seems to be running fine.

Actually I don't think "WARNING: Can't find stage Test App, Therefore, aborting focusing" is related to the fail of GUI test cases.  Because this error message will always appear when I run junit tests even all of them can pass successfully. Perhaps their team's program has another bug?

**Comment by sunset1215** [comment]
Hi prof, my team is facing this issue too. Tests fail on travis side due to this error. Junit tests on eclipse passed though.

**Comment by damithc** [comment]
@sunset1215 give a link to your repo? As @shixiyue said, the error message could be harmless (not relevant to the failure).

**Comment by sunset1215** [comment]
@damithc 
Link to [repo](https://github.com/CS2103AUG2016-T13-C1/main)
build's failing now due to other reasons. could check out the last successful build [here](https://travis-ci.org/CS2103AUG2016-T13-C1/main/builds/172723663)

**Comment by yl-coder** [comment]
The warning message is harmless. I think is a timing issue, but it should not fail any test cases because of this.

**Comment by BrehmerChan** [comment]
> it seems that if we shift the position of commandBox, the guiRobot doesn't clicks on the commandBox position and clicks somewhere else. However our headless test using gradlew seems to be running fine.

> I solved it by making the command box auto-focus: add commandTextField.requestFocus(); 
at the end of method addToPlaceholder() in CommandBox.java. It should work!

I'm currently facing the same problem and the solution provided isn't working for me. I am able to pass the guiTests by running using gradle on headless. Does anyone know how do I go about solving this?

**Comment by damithc** [comment]
Thanks for the update @BrehmerChan 
I'm closing the issue. If anyone else still cannot solve it by tweaking the display resolution, please reopen.
