### ISSUE TITLE
UiParts should not store a reference to the primaryStage

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#183]
Currently, all UiParts [store a reference to their primaryStage](https://github.com/se-edu/addressbook-level4/blob/61b1f6fa5d259677efcd8df61b73b7569b7d5715/src/main/java/seedu/address/ui/UiPart.java#L21), which means that they can potentially modify the primaryStage at their own fancy. This makes it hard to reason about which UiPart is controlling the primaryStage.

Furthermore, only `MainWindow` requires access the primaryStage. All other UiParts do not, but they are still forced to depend on the primaryStage (violates ISP?)

Perhaps the `primaryStage` field should be pushed down from `UiPart` to `MainWindow`. That way, all other UiParts lose access to the primaryStage, which reduces unneeded coupling.

cc @yl-coder 
See also: https://github.com/CS2103AUG2016-T11-C4/main/pull/38/commits/49bbe31a469438ae7e819244db6bf051154a77d1

**Comment by damithc** [comment]
Yes, it sounds like a good idea.
