### ISSUE TITLE
Simplify construction of UiParts

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#184]
Currently there is quite a lot of [boilerplate](https://github.com/se-edu/addressbook-level4/blob/61b1f6fa5d259677efcd8df61b73b7569b7d5715/src/main/java/seedu/address/ui/CommandBox.java#L32-L64) involved if a developer wants to implement a new `UiPart`:

```java
    public static CommandBox load(Stage primaryStage, AnchorPane commandBoxPlaceholder, Logic logic) {
        CommandBox commandBox = UiPartLoader.loadUiPart(primaryStage, commandBoxPlaceholder, new CommandBox());
        commandBox.configure(logic);
        commandBox.addToPlaceholder();
        return commandBox;
    }

    public void configure(Logic logic) {
        this.logic = logic;
        registerAsAnEventHandler(this);
    }

    private void addToPlaceholder() {
        SplitPane.setResizableWithParent(placeHolderPane, false);
        placeHolderPane.getChildren().add(commandTextField);
        FxViewUtil.applyAnchorBoundaryParameters(commandPane, 0.0, 0.0, 0.0, 0.0);
        FxViewUtil.applyAnchorBoundaryParameters(commandTextField, 0.0, 0.0, 0.0, 0.0);
    }

    @Override
    public void setNode(Node node) {
        commandPane = (AnchorPane) node;
    }

    @Override
    public String getFxmlPath() {
        return FXML;
    }

    @Override
    public void setPlaceholder(AnchorPane pane) {
        this.placeHolderPane = pane;
}
```

In short, the developer needs to override:

* `setNode()`
* `setFxmlPath()`
* potentially `setPlaceholder()`

and think of what is the sane thing to do for each of these methods. Additionally, to make the API pleasant to use, the developer also needs to implement a static `load()` method (and in that method, we need to decide which of the three overloaded `UiPartLoader::loadUiPart()` methods we should call)

The reason why is because the current implementation (though `UiPartLoader`) [puts the responsibility on creating new controller instances on the `FXMLLoader`](https://github.com/se-edu/addressbook-level4/blob/master/src/main/java/seedu/address/ui/UiPartLoader.java#L27), but the `FXMLLoader` does not allow us to pass arguments to the constructed controller. This leads to a lot of boilerplate code just to work around this limitation.

By using an approach similar to https://github.com/CS2103AUG2016-T11-C4/main/pull/4 , where we construct the controller *first* and then pass it to the `FXMLLoader`, we can move the FXML loading directly into the `UiPart` constructor and reduce the above code to just:
```java
    public CommandBox(AnchorPane placeHolderPane, Logic logic) {
        super(FXML);
        this.placeHolderPane = placeHolderPane;
        this.logic = logic;
        registerAsAnEventHandler(this);
        addToPlaceholder();
    }

    private void addToPlaceholder() {
        SplitPane.setResizableWithParent(placeHolderPane, false);
        placeHolderPane.getChildren().add(commandTextField);
        FxViewUtil.applyAnchorBoundaryParameters(commandTextField, 0.0, 0.0, 0.0, 0.0);
    }
```
which is much shorter.

cc @yl-coder

**Comment by damithc** [comment]
Sounds like a good idea @pyokagan. 👍
