### ISSUE TITLE
Construct BrowserPanel in FXML

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#186]
The DeveloperGuide states that:
```markdown
The `UI` component uses JavaFx UI framework. The layout of these UI parts are defined in matching `.fxml` files
 that are in the `src/main/resources/view` folder.<br>
 For example, the layout of the [`MainWindow`](../src/main/java/seedu/address/ui/MainWindow.java) is specified in
 [`MainWindow.fxml`](../src/main/resources/view/MainWindow.fxml)
```

While this is mostly true, there is one oddball UiPart that does not have a corresponding `.fxml` file -- [BrowserPanel](https://github.com/se-edu/addressbook-level4/blob/61b1f6fa5d259677efcd8df61b73b7569b7d5715/src/main/java/seedu/address/ui/BrowserPanel.java).

For consistency with the rest of the UiParts, let's construct the `BrowserPanel` using FXML rather than using code.

**Comment by damithc** [comment]
Good point. 👍
