### ISSUE TITLE
Set Up AppVeyor CI

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#192]
Jim is a Windows user, so he would be able to sleep more peacefully at night if he knows that this project is being tested regularly on the operating system he uses.

[AppVeyor](https://www.appveyor.com/) is a Windows CI service that is free for open source projects.

**Comment by damithc** [comment]
Yes that is worth a try. We can use both Tavis and AppVeyor at the same time, right? Do you have experience with AppVeyor @pyokagan ?

**Comment by pyokagan** [comment]
@damithc 
> We can use both Travis and AppVeyor at the same time, right?

Yep. I have them both running on my fork.

> Do you have experience with AppVeyor @pyokagan ?

Nope :-P It's just something I wished I had during the project phase.

Of course, if someone with more experience would like to provide input or take over this issue that would be great.

**Comment by damithc** [comment]
@pyokagan PowerPointLabs uses AppVeyor but the person who set it up is no longer an active dev in the team. So we'll have to depend on you to set it up for now :-)

**Comment by pyokagan** [comment]
Whoops, fixed in #218  :-P
