### ISSUE TITLE
Make Travis CI output less verbose

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#204]
The job log produced by Travis CI is extremely verbose, making it hard to spot what exactly caused a build to fail.

Take a look at the job logs at https://travis-ci.org/se-edu/addressbook-level4 for examples.

Find a way to make the output less verbose, while still providing enough information for effective error diagnosis.

**Comment by Zhiyuan-Amos** [comment]
https://gist.github.com/nlochschmidt/5df1a5398262e0aec815
