### ISSUE TITLE
After executing an incorrect command, reposition caret at the end of the command

### ISSUE THREAD

**Issue by edmundmok** [se-edu/addressbook-level4#205]
Currently, typing an incorrect command will first clear the command box then restore the previous incorrect command. As such, the caret position will be at the extreme left on incorrect commands. I think it would be more natural to the user if the caret retains its last position.

This is easily changed by:
```java
   /**
     * Restores the cursor position to be at the end of the previously entered command
     */
    private void restoreCursorPosition() {
        commandTextField.positionCaret(previousCommandText.length());
    }
```
One possible downside is that multiple incorrect commands (e.g. multiple incorrect adds) in a row might seem unresponsive to the user since there is no other feedback now. 

BTW, I am not sure where to make suggestions as I am new to this, hope this is the right place to do so.

**Comment by damithc** [comment]
Yes, it can certainly improve the user experience. Thanks for the suggestion @edmundmok

**Comment by cheec** [comment]
Hi @edmundmok, as you said "I think it would be more natural to the user if the caret retains its last position". Doesn't your suggestion instead move the caret position to the extreme right every time? May I suggest instead we do exactly as you said - we store the previous caret position after each input, upon an incorrect command, we restore this previous caret position i.e.

```java
private void handleCommandInputChanged() {
    previousCommandText = commandTextField.getText();
    previousCaretPosition = commandTextField.getCaretPosition();
    ...
    ...
}
```
```java
private void restoreCommandText() {
    commandTextField.setText(previousCommandText);
    commandTextField.positionCaret(previousCaretPosition);
}
```
This should work appropriately I think.

**Comment by edmundmok** [comment]
Oh yea, that's true.

**Comment by pyokagan** [comment]
Actually, I think this issue may be a symptom of a larger problem -- that (mis)using events to signal errors leads to more convoluted code such as how CommandBox has to clear its input after a command, thinking its successful, and then restoring its input after it realises that the command was not actually successful.

Special return values or exceptions may be a better fit for signaling errors.

**Comment by damithc** [comment]
Perhaps we can tweak the CommandResult class to indicate if the command execution was successful and use the resulting CommandResult object to decide what the command box should do after executing a command, instead of the current convoluted use of events.
