### ISSUE TITLE
Warn user when inputting multiple values of same type

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#206]
The following command: `add John Doe p/91234567 p/98765432 a/Block 123, Java Street 32 a/Block 321, C Street 23 e/johndoe@gmail.com e/johndoe@yahoo.com` will generate the person card with the following details:

`John Doe`
`98765432`
`Block 321, C Street 23`
`johndoe@yahoo.com`

In such an event, should all the fields be captured in the person card i.e:
`John Doe`
`91234567` `98765432`
`Block 123, Java Street 32` `Block 321, C Street 23`
`johndoe@gmail.com` `johndoe@yahoo.com`

Or should an error be thrown?

**Comment by damithc** [comment]
Based on our current design, a person can have only one telephone number. So we should not capture multiple values unless we expand our features to allow multiple phone numbers.
If a user types multiple values, that must be a mistake. We can either reject the command or accept the last value. In the case of the latter, it is ideal if we can also give a warning.

**Comment by damithc** [comment]
From a usability perspective, taking the last value and giving a warning is friendlier than rejecting outright? The last value is most likely to the intended value.
