### ISSUE TITLE
Update URL of help window

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#217]
Currently the help window loads https://github.com/se-edu/addressbook-level4/blob/master/docs/UserGuide.md

We can update the help window to point to https://se-edu.github.io/addressbook-level4/docs/UserGuide.html so that the user guide looks more like a user guide rather than a Github repo :-)

**Comment by damithc** [comment]
On a related note, I've tried a few different themes and none of them seem to render the pages as intended (or as clean as the default markdown rendering). :-p
e.g. 
![image](https://cloud.githubusercontent.com/assets/1673303/21292608/7e86a93a-c546-11e6-9ddc-7c5a1698a9bc.png)
![image](https://cloud.githubusercontent.com/assets/1673303/21292609/8be50e50-c546-11e6-8b7d-4415845b9674.png)

**Comment by pyokagan** [comment]
@damithc I think Github uses a different markdown rendering engine for github.io vs github.com, so some syntax that parses correctly on github.com may not parse on github.io

E.g., I could fix up some of the rendering with the following patch:
```diff
diff --git a/docs/UserGuide.md b/docs/UserGuide.md
index 507ba15..05b4cdc 100644
--- a/docs/UserGuide.md
+++ b/docs/UserGuide.md
@@ -7,9 +7,11 @@
 
 ## Quick Start
 
-0. Ensure you have Java version `1.8.0_60` or later installed in your Computer.<br>
-   > Having any Java 8 version is not enough. <br>
-   This app will not work with earlier versions of Java 8.
+0. Ensure you have Java version `1.8.0_60` or later installed in your Computer.
+
+    > Having any Java 8 version is not enough.
+    >
+    > This app will not work with earlier versions of Java 8.
    
 1. Download the latest `addressbook.jar` from the [releases](../../../releases) tab.
 2. Copy the file to the folder you want to use as the home folder for your Address Book.
@@ -30,6 +32,7 @@
 ## Features
 
 > **Command Format**
+>
 > * Words in `UPPER_CASE` are the parameters.
 > * Items in `SQUARE_BRACKETS` are optional.
 > * Items with `...` after them can have multiple instances.
```

**Comment by damithc** [comment]
Yes, github.io markdown parser seems to be stricter.

**Comment by damithc** [comment]
Upping the priority because it's good if this can be done before this semester's cohort reaches level 4
