### ISSUE TITLE
Explore using @canihasreview for PR revision management

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#243]
With the rebase workflow (e.g. the one used in #209), it is necessary to generate commit listings to:

1. View the list of commits in their correct (topological) order (GitHub lists commits in date order instead
2. Have identifiers to refer to individual commits (e.g. `[v2 1/8]`)
3. Track how a commit series evolves with time.

https://pyokagan.github.io/prsummary-generator/ is one tool for doing this which accomplishes (1) and (2) well. However it does not accomplish (3) at all, since it does not archive the commits at that moment in time. As such, when the PR author force pushes, the commits of the previous revision are lost.

Furthermore, GitHub's "changes since last review" (the interdiff) doesn't work with a rebase workflow.

@canihasreview (https://canihasreview.herokuapp.com/, e.g. https://canihasreview.herokuapp.com/se-edu/addressbook-level4/pull/237) is an experimental service that aims to solve the above problems. It generates proper commit listings for a PR, archives it and also generates an interdiff wrt the previous version. It even gives you a copy-paste command line to encourage reviewers to checkout the PR locally on their system.

Let's test trial it and see if it works well :-)

Example of a "review request":

![tmpscreen](https://cloud.githubusercontent.com/assets/109479/21581283/7ee16138-d066-11e6-90dc-eefb6d936c61.png)

**Comment by pyokagan** [comment]
@damithc Is it possible to give @canihasreview write access to the addressbook repos so that it can store its internal data (e.g. archives, interdiffs) ? Thanks!

**Comment by damithc** [comment]
@pyokagan 
When I try to give write access, Github says @canihasreview is not a GitHub user.

**Comment by pyokagan** [comment]
@damithc It's without the `@` in front.

**Comment by pyokagan** [comment]
Source code is available at https://github.com/pyokagan/canihasreview

With https://github.com/pyokagan/canihasreview/pull/1 , the `s.ToReview` label should now be set on PRs that requested review.

**Comment by damithc** [comment]
Nice 👍 
1. Does it also remove other existing `s.` labels? 
2. Are you planning to add some usage instructions somewhere?

**Comment by pyokagan** [comment]
@damithc 
> Does it also remove other existing s. labels?

Yes it will. (Read: it should :-P )

> Are you planning to add some usage instructions somewhere?

Yeah. I plan to add lots of things as well, the only problem is time :-P

**Comment by damithc** [comment]
Decision: fit enough for current needs. Adopt.
