### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#249]
A new version should be released as there have been significant behavior changes since the last release

**Comment by Zhiyuan-Amos** [comment]
Prof when should we release a new version?

**Comment by damithc** [comment]
We haven't done that in a while :-p
Can do one now and after that, we can do that periodically provided there are enough behavioral changes.

**Comment by yamgent** [comment]
What version number should we use for the new version. Version 1.4?

**Comment by damithc** [comment]
> What version number should we use for the new version. Version 1.4?

Sure

**Comment by pyokagan** [comment]
@Zhiyuan-Amos Need to remember to change the version number. https://github.com/se-edu/addressbook-level4/blob/89889b9a0bb1c75b945d41466adc4bec50f9a72e/src/main/java/seedu/address/MainApp.java#L43

**Comment by Zhiyuan-Amos** [comment]
Noted, thanks much for your reminder Paul :)

**Comment by yamgent** [comment]
https://github.com/se-edu/addressbook-level4/releases v1.4 needs to be updated to point to the correct commit and the corrected .jar file.
