### ISSUE TITLE
New architecture for GUI unit test

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level4#280]
In response to https://github.com/se-edu/addressbook-level4/pull/260#issuecomment-275597691:

The current GUI testing architecture uses `TestApp`, which by itself inherits `MainApp`. This means that all `UiPart`s in our main window will be initialized. However, it is not necessary to have all the components available when we are only testing a single `UiPart`. It also makes it hard to isolate the individual `UiPart`, as `UiPart`s generally influences each other (e.g. testing the `CommandBox` might result in a change in `StatusBarFooter`.

Therefore, I propose a new class, `GuiUnitTestApp`, which will just be a blank window but allows each individual GUI unit test to insert the `UiPart` that they are testing into the blank window. That way, isolation is achieved.

This architecture is in action in https://github.com/se-edu/addressbook-level4/pull/260.

---

![uml](https://cloud.githubusercontent.com/assets/3168908/22415422/30186cf6-e702-11e6-8da5-afb45b458ff9.png)
_Figure 1: UML of the new proposed architecture_

---

![example](https://cloud.githubusercontent.com/assets/3168908/22415430/5021ea54-e702-11e6-8bd1-89012eebac7a.png)
_Figure 2: PersonCardTest uses GuiUnitTestApp (PR #260)_

**Comment by pyokagan** [comment]
@yamgent 
> This architecture is in action in #260.

So, given that #260 implements this new architecture, technically #260 is fixing this issue rather than #172 , and adding unit tests for the PersonCard class is simply a motivating example for this new architecture.

**Comment by yamgent** [comment]
@pyokagan Ok, will change the PR message then.

**Comment by pyokagan** [comment]
Marking as high priority, it would be great if this could be done asap so that we can stop using workarounds when testing UI code.
