### ISSUE TITLE
Checkstyle: investigate difference between config files

### ISSUE THREAD

**Issue by eugenepeh** [se-edu/addressbook-level4#283]
Currently the checkstyle config file, addressbook is using, seems to have some deviation compare to other major checkstyle config files. 

Investigate the difference against other checkstyle config files such as Google's, ~~Sun's etc.~~

**Comment by damithc** [comment]
Our coding standard is derived from Google's, so it make more sense to compare with Google's checkstyle file.

**Comment by eugenepeh** [comment]
Initial comparison between Addressbook's checkstyle vs Google's checkstyle

Link to addressbook's : https://docs.google.com/document/d/1iz3Dt_5MoPHu7SOHimodfZQ-w8rluFMKgTM92IFWVdw/edit?usp=sharing

Link to google's : https://docs.google.com/document/d/1o3DeKTUxv2zH5j0RtvMXSVTBa0kbGBKWiE_qgtchbZ4/edit?usp=sharing

Red - indicates does not exist on the other checkstyle
Yellow - indicates it exist on the other checkstyle but have different properties
Green - indicates that it exist on the other checkstyle and have same properties

**Comment by damithc** [comment]
Progress noted @eugenepeh Keep us posted.

**Comment by eugenepeh** [comment]
Hello Prof. Damith @damithc , 

Currently the addressbook checkstyle allows both e.g sortList_emptyList_exceptionThrown() and sortList_EmptyList_ExceptionThrown()
(capital letter after underscore).
As this configuration is predefined in the checkstyle file, 
I would like to clarify further with you 
- if this is allowed according to the CS2103 coding convention?

Also 
6. Abbreviations and acronyms should not be uppercase when used as a (OR part of a) name.
bad e.g exportHTMLSource();
For this rule, I believe it can be done by checking that every capital letter is followed by a small letter
- Should it be implemented?

Additionally 
7. Private class variables can have underscore suffix or prefix (not common, but a beneficial practice)
e.g "private String name_;"
Currently this is highlighted as warning by the checkstyle as it doesn't follow MemberName format, 
this can be fixed by allowing this format but 
- Should we also enforce this format?

**Comment by damithc** [comment]
> Currently the addressbook checkstyle allows both e.g sortList_emptyList_exceptionThrown() and sortList_EmptyList_ExceptionThrown()
> (capital letter after underscore).
> As this configuration is predefined in the checkstyle file,
> I would like to clarify further with you
> 
> if this is allowed according to the CS2103 coding convention?

Yes, this is allowed for test cases. However, only the first variation should be allowed.

> Also
> 6. Abbreviations and acronyms should not be uppercase when used as a (OR part of a) name.
> bad e.g exportHTMLSource();
> For this rule, I believe it can be done by checking that every capital letter is followed by a small letter
> 
> Should it be implemented?

Yes, it is good to enforce it if possible.

> Additionally
> 7. Private class variables can have underscore suffix or prefix (not common, but a beneficial practice)
> e.g "private String name_;"
> Currently this is highlighted as warning by the checkstyle as it doesn't follow MemberName format,
> this can be fixed by allowing this format but
> 
> Should we also enforce this format?

No, I plan to remove that guideline. We should not prefix private variable names with underscore.

**Comment by pyokagan** [comment]
@eugenepeh Finished investigating? :-P
