### ISSUE TITLE
Inconsistent parameter name in Parser method

### ISSUE THREAD

**Issue by PierceAndy** [se-edu/addressbook-level4#284]
In [Parser](https://github.com/se-edu/addressbook-level4/blob/master/src/main/java/seedu/address/logic/parser/Parser.java#L48), user input strings are split into `commandWord` and `arguments`, where `commandWord` stores the command string such as "add" or "edit", and `arguments` stores everything else that comes after `commandWord`.

[`Parser:parseIndex`](https://github.com/se-edu/addressbook-level4/blob/master/src/main/java/seedu/address/logic/parser/Parser.java#L280-L292) takes the string index extracted from `arguments`, tries to convert it into an integer, and returns `Optional<Integer>`.

However, the method signature is currently `parseIndex(String command)`, which is not accurate as it does not deal with the `commandWord`. It could be changed to `parseIndex(String index)`.

**Comment by damithc** [comment]
@PierceAndy `index` is not exactly accurate either, am I correct? It's 'index and other remaining arguments'? May be `arguments`?

**Comment by PierceAndy** [comment]
@damithc I thought about calling it `arguments` as well, but `parseIndex()` does not actually extract the index from `arguments`. It tries to convert a string into a positive unsigned integer, and wrap it in an Optional object.

With commands such as delete, `arguments` solely comprises of the index of the person to delete. In which case, `arguments` can be passed into `parseIndex()` as it is.

However with commands such as edit, `arguments` contains the index, prefixes (e.g. "/t") , and their respective values (e.g. "friend"). The string containing only the index is first extracted using the `ArgumentTokenizer` class, and it is then passed into `parseIndex()`.

**Comment by damithc** [comment]
In that case `index` sounds right.

**Comment by Zhiyuan-Amos** [comment]
invalidated by #423
