### ISSUE TITLE
Document how to save project docs as pdf files

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#287]
We need to explain how to use Chrome's 'save as pdf' option to save GitHub pages version of the documents in pdf format without losing hyperlinks.

Can be documented under DevGuide, Dev Ops section.

**Comment by damithc** [comment]
@kychua can take this?

**Comment by kychua** [comment]
ok, will include in PR for #270

**Comment by damithc** [comment]
@kychua this is not specific to asciidoc. This info need to be merged in the next few days because the current batch of students need this info although they will not be using asciidoc.
