### ISSUE TITLE
Clean up TestUtil.java

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#295]
Some header comments have empty `@return`s. Some method names can be improved. Some public methods can be given header comments. etc.

**Comment by pyokagan** [comment]
Generally I think that TestUtil has very low cohesion; it is just a giant mix of methods thrown together with little design direction. I think it would be great if the methods could be categorized and split up into more well-defined utility classes.

e.g. `TestUtil#assertThrows()` could be placed in a class dedicated to asserts.

**Comment by ylhlh** [comment]
@pyokagan I'm new to this and would like to handle the cleaning up first, then make another issue for splitting it up into different classes after the cleaning up is merged. Is that okay?
