### ISSUE TITLE
Config#addressBookName is unused

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#307]
[`Config#addressBookName`](https://github.com/se-edu/addressbook-level4/blob/d741336a16662b675c117ed2aa3ade11a934f24c/src/main/java/seedu/address/commons/core/Config.java#L18) is unused and should be removed.

**Comment by Zhiyuan-Amos** [comment]
I don't see it in the code base anymore ^^ will close this issue.
