### ISSUE TITLE
ArgumentTokenizer: ensure tokenizing before getting values

### ISSUE THREAD

**Issue by PierceAndy** [se-edu/addressbook-level4#312]
ArgumentTokenizer's tokenized argument getter methods can be accessed before ArgumentTokenizer is given arguments to tokenize through ArgumentTokenizer#tokenize(String). 

Furthermore, the getter methods in `ArgumentTokenizer`, `getValue(Prefix)`, `getAllValues(Prefix)`, and `getPreamble()`, don't give a warning when they are called before `ArgumentTokenizer#tokenize(...)` is ever called.

This behaviour is problematic as the getters can be called before ArgumentTokenizer#tokenize(...) without any warnings, and would return empty optionals, lists, and strings that are indistinguishable from normal empty results.

[Link to discussion that highlighted this issue](https://github.com/se-edu/addressbook-level4/pull/261#discussion_r103476184)

**Comment by PierceAndy** [comment]
Thoughts? @yamgent

**Comment by PierceAndy** [comment]
Thoughts? @MightyCupcakes

**Comment by MightyCupcakes** [comment]
Yes, I agree. I am also in favour of not using assertions for public methods. This is a public API meant for command parsing, developers new to the API might not know the tokenize method needs to be called before any of the getters.

Throwing an appropriate exception to alert the wrong usage of the API is always better as developers can detect and correct the error early and quickly.

**Comment by damithc** [comment]
A constraint `foo() should be called before bar()` is a sign of a fragile API. Do some research on whether there is a pattern/idiom that avoid the problem altogether?

**Comment by PierceAndy** [comment]
Good point.

A better implementation would be to make use of the factory pattern, where `ArgumentTokenizer#tokenize()` returns an object that has the methods `getValue()`, `getAllValues()`, and `getPreamble()`, such that these methods cannot be called without calling `ArgumentTokenizer#tokenize()`  first.
