### ISSUE TITLE
Break down LogicManagerTest into separate tests

### ISSUE THREAD

**Issue by chao1995** [se-edu/addressbook-level4#327]
`LogicManagerTest` is too ambitious. It contains 500+ lines of code at the moment and tests **all** commands in integration test level.

We can break it down to command-specific tests.

Note that tests failing at parsing should be moved to parser's unit test, while the rest should be moved to command's Integration Test.

**Comment by Zhiyuan-Amos** [comment]
@chao1995 Hello, can I know what's the progress for this issue (particularly, why is your PR closed?)? Would like to work on it :) Thank you!

**Comment by chao1995** [comment]
Hi @Zhiyuan-Amos 

> can I know what's the progress for this issue (particularly, why is your PR closed?)?

The closed basically is an attempt to copy and paste code to different files. However, during the code review, it seems that the problem of `LogicManagerTest` is that `LogicManagerTest` only needs to (and should only) cover all the different paths in `LogicManager`. Since I was working on `EditCommandIntegrationTest` then, I decided to work on that PR first.

So now, I think we can bring those integration level tests from `LogicManagerTest` to `XXXCommandIntegrationTest` by following a similar structure as `EditCommandIntegrationTest`, and create a base class for integration test, e.g. `CommandIntegrationTest` when it's appropriate to do so.

Note that some tests in `LogicManagerTest` should actually be tested in unit tests level, most likely as unit tests for the parsers.

**Comment by Zhiyuan-Amos** [comment]
@chao1995 Thanks for the thorough explanation!

Can I know what's the motivation for creating a `CommandIntegrationTest`? Does it work as a helper / utilities class in which all the `XXXCommandIntegrationTest` uses?

**Comment by chao1995** [comment]
> Can I know what's the motivation for creating a CommandIntegrationTest? Does it work as a helper / utilities class in which all the XXXCommandIntegrationTest uses?

Its purpose is similar to `AddressBookGuiTest` for those specific gui tests like `AddCommandTest`.

So common methods for integration testings like `assertCommandSuccess`, `assertCommandFailure` and `prepareCommand` in `EditCommandIntegrationTest` can be extracted to a base class, i.e. `CommandIntegrationTest`. I didn't do this before because at that time it's not clear which methods should eventually go to the base class. But when you are developing the next integration tests for other commands like `add`, you can see more easily which methods are reused, and then extracted them into a base class.

**Comment by Zhiyuan-Amos** [comment]
Ah I see. Alright great, thanks @chao1995 ! :)

**Comment by damithc** [comment]
Hang on. LogicManager is a very small class. The LogicManagerTest should be similarly small. After we have moved the bulk of the tests in LogicManagerTest to lower levels, I don't think there will be a need to break it up any more. What do you guys think?

**Comment by Zhiyuan-Amos** [comment]
Yup, sounds right to me.

**Comment by chao1995** [comment]
> LogicManager is a very small class. The LogicManagerTest should be similarly small. After we have moved the bulk of the tests in LogicManagerTest to lower levels, I don't think there will be a need to break it up any more.

Yes, agree. I think breaking it up is referring to moving those tests to either lower levels (i.e. unit test), or more specific integration tests of commands.

**Comment by chao1995** [comment]
> LogicManager is a very small class. The LogicManagerTest should be similarly small. After we have moved the bulk of the tests in LogicManagerTest to lower levels, I don't think there will be a need to break it up any more.

Yes, agree. I think breaking it up is referring to moving those tests to either lower levels (i.e. unit test), or specific integration tests for individual commands.

**Comment by yamgent** [comment]
Fixed by #495.
