### ISSUE TITLE
Model filtering not easily extensible

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#334]
In our [Model filtering API](https://github.com/se-edu/addressbook-level4/blob/297506b87fabe6de6baa7901388039ec50199802/src/main/java/seedu/address/model/Model.java#L40-L44), we have:

* `updateFilteredListToShowAll()`, to remove any active filter, and
* `updateFilteredPersonList(Set<String>`), to filter persons by their name,

...and, that's all. If we need any other filtering method, we will need to modify the model source code directly.

It would be nice if we could easily extend the Model filtering functionality with our own custom filters without needing to modify its source code.

**Comment by yamgent** [comment]
Perhaps we can implement a `updateFilteredPersonList(Predicate<? super ReadOnlyPerson>)`, and create a new helper class to generate commonly used filters.
