### ISSUE TITLE
AppVeyor: limit time a build can take

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#341]
AppVeyor only allows us to run one build at a time (other builds will wait), so it is important that we ensure that a single build from a bad PR cannot hold up the entire queue.

OTOH, AppVeyor actually already has a hard limit on run time, but it is quite long (longer than 1 hr), and we definitely can't afford to wait that long :-P

So, we probably need to enforce a much shorter limit on our side. Our (successful) builds currently take around 5 minutes. To be conservative we could limit builds to around 10 minutes. AppVeyor does not allow us to specify our own limits (?) so we probably need a wrapper script or something.

**Comment by Zhiyuan-Amos** [comment]
https://github.com/appveyor/ci/issues/517 Seems like we can ask the devs to configure on their end. @yamgent

**Comment by yamgent** [comment]
The requests on that thread are all asking for lengthening of the time-out, not shortening (lengthening build time means more resources utilized on AppVeyor side, so the existence of such a thread is pretty understandable).

Having a middleman to adjust our time-out seems to be troublesome, and should be considered as a last resort when doing something that is not possible on our side. Suppose that our requirements of build time change in the future, we would have to ask again.

Unless they implement a setting usable inside AppVeyor.yml, I would still prefer a solution where we limit the build time on our side, by running a wrapper script that would automatically terminate and fail after X minutes, if gradle does not terminate by then.

**Comment by pyokagan** [comment]
Not really needed, really. Can revive this issue when it actually becomes a problem.
