### ISSUE TITLE
Organise test data generation

### ISSUE THREAD

**Issue by chao1995** [se-edu/addressbook-level4#348]
Currently, at least

- `TypicalPersons`
- `LogicManagerTest#TestDataHelper`
- some methods in `TestUtil` (e.g. `getSamplePersonData()`)

have methods relating to generate test data.

Also, we have `PersonBuilder`. So for example, I think methods relating to generate test persons should be moved to there. Similarly, we might want to have `AddressBookBuilder` etc.

**Comment by Zhiyuan-Amos** [comment]
@yamgent is there a need to shift test generation data from `TypicalPersons` to `PersonBuilder`? I'm not sure hmm

**Comment by yamgent** [comment]
I think they should all belong in a same class, but not necessary `PersonBuilder`. Put them all in `TestDataHelper` class?

**Comment by Zhiyuan-Amos** [comment]
So `TestDataHelper` contains `PersonBuilder`, `TypicalPersons` and `AddressBookBuilder`?

**Comment by yamgent** [comment]
I mean the variables and methods should at least be in one cohesive class such as `TestDataHelper`. The classes `PersonBuilder`, `TypicalPersons`, etc, should not be inside another class.

**Comment by Zhiyuan-Amos** [comment]
ps don't get what you're saying. Can you list some examples of variables and methods that should be inside `TestDataHelper`?

**Comment by yamgent** [comment]
Sorry I read this issue wrongly. The main problem is no longer valid as `LogicManagerTest#TestDataHelper` no longer exist, and you are removing the methods for `TestUtil` in #560 (because they are just duplicate of `TypicalPersons`). I am fine with everything being in `TypicalPersons` for now.

**Comment by Zhiyuan-Amos** [comment]
Noted, that way my PR fixes this issue as well then :)
