### ISSUE TITLE
Fix errors in GUI tests when upgrading to the new version (4.0.6-alpha) of TestFx

### ISSUE THREAD

**Issue by chao1995** [se-edu/addressbook-level4#358]
An extension of #353.

Previously #354 fixes the GUI tests error by fixing the TestFx to an older version (4.0.5-alpha). However, we need to find out what is the reason causing GUI tests to fail when upgrading to the new version (4.0.6-alpha) of TestFx.

**Comment by VeryLazyBoy** [comment]
In 4.0.6-alpha, the method `getParameters` in `MainApp#getApplicationParameter(...)` is supposed to return a object of `Application.Parameter` with empty fields when there is no parameters passed to the application. However, it seems that `getParameters` gives a null value instead in this new version of TestFX, which causes a `NullPointerException`.

**Comment by chao1995** [comment]
@VeryLazyBoy Thanks for looking into this! I saw you closed the PR. why?

**Comment by VeryLazyBoy** [comment]
Because I think, instead of changing our own code to comply with TestFX, choosing a stable version of it might be a right way?  I really don't understand why TestFX has changed the behavior of `getParameters`. According to Javadoc of `javafx.application.Application#getParameters`, `getParameters` shouldn't return null when it is called inside `init`. Perhaps, our guitest failures are due to TestFX's own fault?

**Comment by damithc** [comment]
@VeryLazyBoy you can file a bug report with TestFx and see what they say.

**Comment by VeryLazyBoy** [comment]
I got a reply from TestFX. In 4.0.6-alpha, to increase compatibility of Java 9, they remove a private API which is used to register parameters of JavaFX application. As a result, the parameters for application are not correctly passed. It seems that they are finding a way to rectify the problem. **Here is the link to** [**their reply**](https://github.com/TestFX/TestFX/issues/380)

**Comment by pyokagan** [comment]
Hrm, a new TestFX version hasn't been released yet?

Anyway, I'm personally interested in upgrading to 4.0.6-alpha because it makes headless mode in Linux work. With 4.0.5-alpha, it would just error out with `IllegalAccessException` :-(

Quick patch:
```diff
diff --git a/build.gradle b/build.gradle
--- a/build.gradle
+++ b/build.gradle
@@ -40,8 +40,8 @@ allprojects {
         jacksonVersion = '2.7.0'
         jacksonDataTypeVersion = '2.7.4'
         junitVersion = '4.12'
-        testFxVersion = '4.0.5-alpha'
-        monocleVersion = '1.8.0_20'
+        testFxVersion = '4.0.6-alpha'
+        monocleVersion = '8u76-b04'
         checkstyleVersion = '7.2'
 
         libDir = 'lib'
diff --git a/src/main/java/seedu/address/MainApp.java b/src/main/java/seedu/address/MainApp.java
index 12812b6..8080498 100644
--- a/src/main/java/seedu/address/MainApp.java
+++ b/src/main/java/seedu/address/MainApp.java
@@ -1,6 +1,7 @@
 package seedu.address;
 
 import java.io.IOException;
+import java.util.HashMap;
 import java.util.Map;
 import java.util.Optional;
 import java.util.logging.Logger;
@@ -76,7 +77,8 @@ public class MainApp extends Application {
     }
 
     private String getApplicationParameter(String parameterName) {
-        Map<String, String> applicationParameters = getParameters().getNamed();
+        Map<String, String> applicationParameters =
+                getParameters() != null ? getParameters().getNamed() : new HashMap<>();
         return applicationParameters.get(parameterName);
     }
 
```
