### ISSUE TITLE
Add assertions

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#38]
Add java `assert` s where appropriate.

**Comment by damithc** [comment]
@YijinL are you working on this?

**Comment by YijinL** [comment]
No, I don't think I have the time. Might be easier to do it for one component and have the rest be a student exercise? Stuff like ui components or commands that need extra dependencies added, asserting their existence in the `execute` or `start` method seems very obvious.

**Comment by damithc** [comment]
Got it. I'll do it.

**Comment by damithc** [comment]
Added some assertions to storage component
