### ISSUE TITLE
Shorten names of constants of Person's attributes

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#399]
Each of these classes: `Name`, `Phone`, `Email`, `Address` and `Tag` has a `MESSAGE_X_CONSTRAINTS` and `X_VALIDATION_REGEX` (X referring to the name of the class).

It is unnecessary to have `X` as part of the names of these constants. For example, `Name.MESSAGE_NAME_CONSTRAINTS` doesn't seem to provide more information than `Name.MESSAGE_CONSTRAINTS`.

**Comment by Zhiyuan-Amos** [comment]
@yamgent your thoughts please :)

**Comment by yamgent** [comment]
Good point. We certainty can fix that.

**Comment by Zhiyuan-Amos** [comment]
@yamgent we can let the other person joining us do ba :P
