### ISSUE TITLE
Parser should notify all values that are unsuccessfully parsed

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#407]
Parser only complains about the first value that is unsuccessfully parsed. 
`edit 1 n/* e/yahoo!!!` has illegal values for both `Name` and `Email`, however the parser only complains that the name is invalid.

**Comment by pyokagan** [comment]
@Zhiyuan-Amos Maybe reconsider this for `s.DeferredToFutureForks`? This may require a "undo/redo v2"-level of effort to implement.
