### ISSUE TITLE
Search substring will return incorrect feedback message

### ISSUE THREAD

**Issue by yl-coder** [se-edu/addressbook-level4#41]
List has this two person
benson and fiona. 

Both have substring of "on". Therefore feedback will be 2 persons listed. However it is returning 0 person listed now.

**Comment by damithc** [comment]
I thought we don't have substring search? @YijinL

**Comment by YijinL** [comment]
Yes, it's full keyword search. No partials

**Comment by yl-coder** [comment]
I guess there something wrong with level 4 filtering then. Will fix it
