### ISSUE TITLE
PersonListPanel background becomes white when no Person is listed

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level4#415]
Normally, the background of the `PersonListPanel` is gray in color.

![white-box-one-person-listed](https://cloud.githubusercontent.com/assets/3168908/26086391/e732bf00-3a1c-11e7-832b-464ad420a0ef.png)

However, if no person gets listed (e.g. `find keyword_that_does_not_exist_in_any_person_name`), the background suddenly changes to white:

![white-box-zero-person-listed](https://cloud.githubusercontent.com/assets/3168908/26086395/ecf1e862-3a1c-11e7-8222-43ca275dbe1c.png)

This is rather ugly because it stands out rather prominently. Fix it so that the gray color remains even when no person is listed.

**Comment by pyokagan** [comment]
No solution was given in the issue description, so this issue shouldn't have been marked as `d.FirstTimers` :-P

With that said, there is a solution here: https://github.com/nus-cs2103-AY1718S1/forum/issues/86
