### ISSUE TITLE
Add warning message field for CommandResult 

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level4#416]
`CommandResult` only has a single field `feedbackToUser`. It is used only for a single purpose (either for success or for failure).

There may be cases where commands have both a successful message + warning message.

* Modify the `CommandResult` class to include another `String` for a warning message.
* Modify the GUI to support having different variety of message (e.g. white text for successful message, yellow text for warning message displayed right below it). Suggested component to do that: [JavaFX's TextFlow class](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/text/TextFlow.html).

**Comment by Zhiyuan-Amos** [comment]
Should we close this? #404 is resolving this but referencing to another issue.

**Comment by yamgent** [comment]
Superseded by #457.
