### ISSUE TITLE
LogicManager constructor takes in a redundant Storage parameter

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level4#437]
The LogicManager does not utilize the Storage in any way. Therefore it is a redundant parameter.

```
    public LogicManager(Model model, Storage storage) {
        this.model = model;
        this.parser = new Parser();
    }
```

However, this issue will become irrelevant if we fix #158 / merge #212, although PR #212 is on hold due to YAGNI principle.

**Comment by Zhiyuan-Amos** [comment]
I will fix this since #212 is on hold and YAGNI applies to #158 as well.
