### ISSUE TITLE
Model should throw IndexOutOfBoundsException if index for filtered list is out of bounds

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level4#446]
`EditCommand` and `DeleteCommand` checks whether the index is valid and belongs to a Person in the Model's filtered list.

That should not be the job of the `Command`s, as they should not be aware of the list in the first place. The index validation check should be done in `Model` instead (the owner of the list), and if the check fails, there should be an ~~`IndexNotInListException`***~~ `IndexOutOfBoundsException` for the `Command` to catch and handle with an appropriate message.

Let's:
* Move the logic of checking the validity of the index from `EditCommand#execute()` and `DeleteCommand#execute()` to `Model.updatePerson(...)` and `Model.deletePerson(...)` respectively
* Change `Model.deletePerson(ReadOnlyPerson)` to `Model.deletePerson(Index)`.

~~***`IndexNotInListException` will be a checked exception, unlike `IndexOutOfBoundsException` which is a runtime exception.~~

**Comment by pyokagan** [comment]
Checked exceptions start to become problematic when we end up with code like:
```java
try {
    model.deletePerson(indexWeKnowIsValidBecauseWeValidatedItAsPartOfAnotherOperationEarlier);
} catch (IndexNotInListException) {
    throw new AssertionError("should not happen");
}
```
all over the place.

**Comment by yamgent** [comment]
> Checked exceptions start to become problematic when we end up with code like:
> 
> try {
>     model.deletePerson(indexWeKnowIsValidBecauseWeValidatedItAsPartOfAnotherOperationEarlier);
> } catch (IndexNotInListException) {
>     throw new AssertionError("should not happen");
> }
>
> all over the place.

Agree, perhaps that is a good reason to just use `IndexOutOfBoundsException`.

**Comment by pyokagan** [comment]
@yamgent 
> perhaps that is a good reason to just use IndexOutOfBoundsException.

Then it becomes using exceptions for flow control :-P

I think the current situation of leaving bounds checking to the callers is okay. Java programmers should be used to it anyway, since the Java collections library also requires that.

I agree that this:
> Change Model.deletePerson(ReadOnlyPerson) to Model.deletePerson(Index).

is worth doing though.
