### ISSUE TITLE
HelpCommand#setData and ExitCommand#setData should be overwritten

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#451]
`HelpCommand#setData` and `ExitCommand#setData` are currently assigning `model` to `HelpCommand` and `ExitCommand` respectively.

There is no need for `HelpCommand` and `ExitCommand` to have access to `model`. 

Let's overwrite `HelpCommand#setData` and `ExitCommand#setData` to not assign `model` to their respective classes.

**Comment by pyokagan** [comment]
Incidentally fixed by #898
