### ISSUE TITLE
Create an ExecutionResult class

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level4#457]
`CommandResult` only has a single field `feedbackToUser`. It is used only for a single purpose (either for success or for failure).

Parsers may also have warnings, but they should not be included in `CommandResult`.

* Create a new `ExecutionResult` class so that `LogicManager#execute()` can return this instead, allowing us to return feedback from the command and warnings from the parser.
* Modify the GUI to support having different variety of message (e.g. white text for successful message, yellow text for warning message displayed right below it). Suggested component to do that: [JavaFX's TextFlow class](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/text/TextFlow.html).

**Comment by Zhiyuan-Amos** [comment]
https://github.com/se-edu/addressbook-level4/pull/404#pullrequestreview-41910239

Will leave this as `p.Zero`
