### ISSUE TITLE
Rework GuiRobot and GuiHandle

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#459]
List of things that need to be done (just ideas for now, for internal discussion and will update as discussions proceed):

* [x] `GuiRobot`: useless class or not? Some methods from the base `GuiHandle` can be moved into `GuiRobot`.
* [x] `GuiHandle` contains a mixture of window and node operations. Likewise, some gui handles (e.g. `PersonCardHandle`, `StatusBarFooterHandle`) represent nodes while others (e.g. `HelpWindowHandle`) represent windows. Some refer to both. We should properly separate them and make them distinguishable.
* [x] No levels of abstraction -- all Gui Handles work directly on global state (list of all nodes in all windows) and have access to the primary stage. Information hiding is haphazard (e.g. `getTextFromLabel(String fieldId, Node parentNode)`
* [x] No need to pass around the `GuiRobot`, each gui handle can create their own. (Might need to verify)
* [x]  **All the timed waits** making the GUI tests slow. While they may make it easier to debug GUI tests, they make e.g. Travis builds slow. We could switch them off in headless mode. (Note: some of them are used to wait for operations in other threads to complete (!!), which will be a source of test flakiness. Need to use proper synchronization primitives!)
* [x] Redundant utility methods e.g. `GuiHandle#getTextFieldText`
* [ ] All the tests are in a separate `guitest` package, which is inconsistent with the other tests and also means that they can't access private package classes (if we have any in the future). Test groups should be used instead.

**Comment by Zhiyuan-Amos** [comment]
For the last point, perhaps this article may be useful: https://www.mkyong.com/unittest/junit-categories-test/
