### ISSUE TITLE
TypicalPersons class header comments is empty

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level4#483]
There are no header comments in for `TypicalPerson` in [`TypicalPersons.java`](https://github.com/se-edu/addressbook-level4/blob/master/src/test/java/seedu/address/testutil/TypicalPersons.java#L9). It is just an empty header comment block.

Let's add one.

**Comment by Zhiyuan-Amos** [comment]
Will close this since #571 covers it.
