### ISSUE TITLE
Setup CI and ensure tests are passing

### ISSUE THREAD

**Issue by m133225** [se-edu/addressbook-level4#49]

**Comment by damithc** [comment]
At the moment checkstyle, pmd, and findbugs are failing. Also, the created jar file doesn't run.

**Comment by m133225** [comment]
Hmm, the created jar seems to run fine on my end on both Mac and Windows though...

**Comment by damithc** [comment]
What's the command to use? I used `gradlew build`

**Comment by damithc** [comment]
BTW, need to add those instructions to docs. e.g. how to build, test, etc.

**Comment by m133225** [comment]
It's already added, but probably not so easily found. Can be access from the `README.md` -> `Gradle` -> `building the application JAR`.

The gradle instruction to use is `./gradlew shadowJar`.
