### ISSUE TITLE
Shift event handling methods out of UiManager

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#498]
`UiManager` is catching events such as `JumpToListRequestEvent` which then calls methods to cause the `PersonListPanel` to scroll to the corresponding location.

There is no need for a high-level component such as `UiManager` to catch these events. Rather, the individual components ought to catch these events, as they are already currently handling these events. Using the example given above, the `PersonListPanel` ought to catch the event instead.

**Comment by damithc** [comment]
The current design assumes `MainWindow` is a container for GUI widgets. `UiManager` is the guy who manages GUI-wide logic of the UI (i.e. logic that doesn't belong in one of the individual widgets), which includes handling certain events but not all. The objective was to distribute the responsibilities and prevent `MainWindow` getting bloated.

**Comment by Zhiyuan-Amos** [comment]
@damithc currently, other GUI components such as `ResultDisplay` and `StatusBarFooter` catch their own events as well. As such, there's inconsistency (in the example given in the issue message, the event that `PersonListPanel` is supposed to handle is being caught by `UiManager`), and we should perhaps standardise them.
