### ISSUE TITLE
Rename component controller classes from Abc to AbcController

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level4#509]
Classes such as `CommandBox` and `PersonListPanel` are actually controller classes.

However, this is not immediately obvious.

Let's rename them to `CommandBoxController` and `PersonListPanelController` to better suit the purpose.

In addition, we should add header comments for the controllers to specify which is the view, and which is the controller, so that students would be more appreciative of the MVC pattern in the application.

**Comment by pyokagan** [comment]
If, e.g., `CommandBox` is renamed to `CommandBoxController`, then its initialization would look like:
```java
new CommandBoxController()
```
However, this piece of code actually initializes *both* the controller and the view (the FXML file), so adding the "Controller" suffix is a bit of a misnomer.

**Comment by pyokagan** [comment]
@yamgent Still an issue?

**Comment by yamgent** [comment]
Probably not, the current code still initialises both the controller and the view, hence the renaming isn't suitable.
