### ISSUE TITLE
PersonListPanelHandle: Remove getPersonCardHandle(ReadOnlyPerson) & getPersonCardHandle(int)

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#549]
Both methods return a `PersonCardHandle`, which in turn is being used by `TestUtil#compareCardAndPerson(PersonCardHandle, ReadOnlyPerson)`.

These methods are unnecessary; we can simply use `PersonListPanelHandle#getPerson(int)` to get the `ReadOnlyPerson` belonging to the `PersonCardHandle`. Then, we can compare both person objects directly without having to use `TestUtil#compareCardAndPerson(PersonCardHandle, ReadOnlyPerson)`.

After making this change, `TestUtil#compareCardAndPerson(PersonCardHandle, ReadOnlyPerson)` will also be redundant.

**Comment by yamgent** [comment]
`AddCommandTest` and `EditCommandTest` (guitests) uses `getPersonCardHandle(ReadOnlyPerson)`. Removing it would require the test to stream through the list themselves.

**Comment by Zhiyuan-Amos** [comment]
Yup, both tests use `getPersonCardHandle(ReadOnlyPerson)` in order to call `assertCardMatchesPerson(addedCard, foo);`

I'm of the opinion that replacing `getPersonCardHandle(ReadOnlyPerson)` with `getPerson(ReadOnlyPerson)`, because of YAGNI principle; callers don't use the PersonCardHandle for any other thing except for comparing the internal persons.

**Comment by yamgent** [comment]
> I'm thinking of replacing getPersonCardHandle(ReadOnlyPerson) with getPerson(ReadOnlyPerson)

???

So what is `getPerson(ReadOnlyPerson)` supposed to be doing? :P

```
public ReadOnlyPerson getPerson(ReadOnlyPerson person) {
    return person;
}
```

**Comment by Zhiyuan-Amos** [comment]
@yamgent, as discussed, rmb update the issue tqvm :>

**Comment by yamgent** [comment]
My conclusion is that `getPersonCardHandle(int index)` is just implemented wrongly semantically. I would have expected that method to iterate through all the cards, and return the card that has `card.id.getText() == index`.

But it does not do that in this codebase, as it looks through the list of ReadOnlyPerson, and use ReadOnlyPerson to find the card instead.

This logic still gives us the correct result, as our implementation just happened to be all correct, even though there is no direct link between card and person.

----

I am of the opinion that `getPersonCardHandle(int index)` is still useful. For example, when doing an `add`, I would like to verify that the last card is the new person with the correct particulars. Same for 'edit', 'edit 5' should modify the 5th card that is visible.

**Comment by Zhiyuan-Amos** [comment]
This issue will be closed because much changes will be changed to this issue after #552 is merged.
