### ISSUE TITLE
Capturing screenshots during headless tests causes disruption for Mac users

### ISSUE THREAD

**Issue by m133225** [se-edu/addressbook-level4#55]
Commenting out `GuiTest.captureScreenshot()` (and the renaming of the file) seems to remove the disruption.

**Comment by yl-coder** [comment]
I guess we can remove the screenshot part? Don't seems like anything we can do in a short period of time now.

**Comment by damithc** [comment]
Yes, can remove for now.

**Comment by damithc** [comment]
Or we can limit screenshots for test failures only.

**Comment by yl-coder** [comment]
i think this was removed in one of the PR @damithc merged.
