### ISSUE TITLE
Logic: Update getFilteredPersonList() to return UnmodifiableObservableList

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#553]
`Model` returns `UnmodifiableObservableList` to `Logic`. `Logic` however, returns an `ObservableList` to its callers (currently only `MainWindow` calls this method).

Callers may not know that the `ModelManager` (which implements `Model`) returns a `FilteredList` (subclass of `ObservableList`), and method calls such as `remove` will throw `UnsupportedOperationException` which callers may not have expected to happen.

Let's update `Logic#getFilteredPersonList()` to return an `UnmodifiableObservableList` instead.

**Comment by pyokagan** [comment]
`UnmodifiableObservableList` was removed in d33ffaf0dcc22018968ddf758f8ac424545ccf9
