### ISSUE TITLE
Clean up GUI tests related classes

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#559]
`PersonListPanelHandle` and `PersonCardHandle` are classes that point to their respective nodes (`PersonListPanelHandle` points to the `PersonListPanel`, while `PersonCardHandle` points to `PersonCard`). The purpose of these handles is to encapsulate these nodes by exposing only certain operations that are required by tests.

- [x] Move `PersonListPanelHandle#isListMatching(ReadOnlyPerson...)` as this is somewhat like a test verification method. `PersonListPanelHandle` should have a method that returns a defensive copy of the internal list of `PersonListPanel`.
- [x] Move `PersonCardHandle#isSamePerson(ReadOnlyPerson)` for the same reason above.
- [x] I think that we should not return `Optional` for `getHandleToSelectedCard()`, since when we call a test method, we are expecting it to return us a value. As such, if there's no value, the method should throw an appropriate RuntimeException.
-------
`AddressBookGuiTest` is a class that's attempting to store everything that the subclasses will use. I think that it's purpose is to set up the environment for subclasses (like setting up the stage etc) so that the code does not have to be repeated across all the tests. As such:

- [x] Move test verification methods such as `assertCardMatchesPerson(PersonCardHandle, ReadOnlyPerson)` as these ought to belong to test utility classes.
- [x] Move other random methods like `raise(BaseEvent)`, which ought to belong to test utility classes as well.
- [x] `EventsCenter.clearSubscribers();` is called in `setup()` which is annotated as `@Before`. It's more intuitive to shift it to a method that is annotated `@After`, as clearing the subscribers seem like a tear down method rather than a set up method.
-------
- [x] `GuiRobot`'s access modifiers are wrong. (PAUSE_FOR_HUMAN_DELAY_MILLISECONDS, DEFAULT_WAIT_FOR_EVENT_TIMEOUT_MILLISECONDS, waitForEvent)

**Comment by Zhiyuan-Amos** [comment]
@yamgent for your thoughts since you've been working on ui

**Comment by yamgent** [comment]
Remove -> move into helper classes? Also, how does this fit into our design for our handle methods in the system test PR, `rememberState()` and `checkStateUnchanged()`, which are also helper methods?

**Comment by Zhiyuan-Amos** [comment]
> Remove -> move into helper classes?

Yup that's right, made the changes.

> Also, how does this fit into our design for our handle methods in the system test PR, rememberState() and checkStateUnchanged()

1. You are right that these are helper methods, which is why I'm of the opinion of encapsulating them inside a `StateObject` class or something like that. 

2. Also, I think helper methods can exist inside the Handle classes, but not test verification methods. So for e.g, we have `rememberState()` and `checkStateUnchanged()`, but not `assertStateUnchanged()`. I.e a Handle can store and return to us any information about the object that it is pointing to, but it should not be doing test verification.

**Comment by yamgent** [comment]
But `PersonListPanelHandle#isListMatching(ReadOnlyPerson...)` and `PersonCardHandle#isSamePerson(ReadOnlyPerson)` are not assert methods nor test verification methods. They are merely state comparison methods.

**Comment by Zhiyuan-Amos** [comment]
Ah I see. I get what you're saying. I'm wondering which looks neater to you.

Random test class:
<pre>
...
assertTrue(isListMatching(ReadOnlyPerson...));
...
</pre>

or

<pre>
...
assertEquals(expectedList, actualList);
...
</pre>

Personally, I prefer the latter because `assertEquals` makes it obvious to the reader that we are comparing for equality between 2 lists.

**Comment by yamgent** [comment]
> ...
> assertEquals(expectedList, actualList);
> ...

Seems like that would require a bit of understanding of the internal representation of `PersonListPanelHandle`, which would be close to the border of the Law of Demeter. And that would also require an additional variable for storing the `actualList`.

**Comment by Zhiyuan-Amos** [comment]
> Seems like that would require a bit of understanding of the internal representation of PersonListPanelHandle

IMO not really, I think `PersonListPanelHandle` implementing a `getPersonList()` seems reasonable following the name of the class.

> And that would also require an additional variable for storing the actualList.

Ps actually don't need to store `actualList`. Cos `actualList` == `getPersonList()`.
