### ISSUE TITLE
PersonListPanelHandle: No longer returns PersonCard

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#563]
~~- [ ] `getPersonCardHandle(int)` is redundant and callers should call `getCard(int)` instead.~~
~~- [ ] `getPersonCardHandle(ReadOnlyPerson)` should not return a `PersonCardHandle`, but it should return a `PersonCard`. If callers still want a `PersonCardHandle`, they can construct it simply on their own by calling `new PersonCardHandle(card.getRoot())`.~~

PersonListPanelHandle is a test helper class that encapsulates
PersonListPanel. It has methods that return PersonCard.

Tests should not directly interact with Node objects such as PersonCard
as it breaks the encapsulation of the PersonCard object.

Let's teach existing methods in PersonListPanelHandle to return 
PersonCardHandle instead of PersonCard. 

- [ ] getSelectedCard() -> getSelectedCardHandle()
- [ ] remove getCard(int)

**Comment by Zhiyuan-Amos** [comment]
@yamgent I'm wondering whether we should wrap this line of code with `PersonCardHandle` first before doing the filtering (i.e additional `map` before the `filter`). Not sure whether `PLPH` should work with `PersonCard` directly.

**Comment by yamgent** [comment]
The internal implementation can interact with `PersonCard` if necessary. However, other classes interacting with `PersonListPanelHandle` should be seeing `PersonCardHandle` being returned.
