### ISSUE TITLE
Standardize all test related methods to throw AssertionError instead of checked exceptions

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level4#568]
Some test related methods throw checked exceptions. This is unnecessary as callers are not expected to handle these exceptions, as we are expected to pass valid input into these test methods. As such, we should throw `AssertionError`, since `AssertionError` symbolises programmer error. 

Let's change all test related methods to throw `AssertionError`s instead of checked exceptions. By doing so, we can use lambda expressions to call these methods. As such, let's update the code base to use lambda expressions as well.

E.g `UiPartRule#setUiPart(UiPart<? extends Parent>)` throws a `TimeoutException`.

**Comment by Zhiyuan-Amos** [comment]
I did not throw `AssertionError` for all of them. Some of them I threw `IllegalArgumentException` instead.
