### ISSUE TITLE
TypicalPersons: Make all methods and fields static

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#569]
TypicalPersons is a utility class that creates preset Persons for tests
to use. Some methods and fields are non-static.

This makes it troublesome for test classes to access these preset 
Persons as they have to create a TypicalPersons object prior to
accessing the Person objects.

Let's make all methods and fields in TypicalPersons to be static. Also,
let's update the callers to static import the methods and fields they
require from TypicalPersons.

**Comment by damithc** [comment]
Keep in mind that making everything static can cause state leaks between tests.

**Comment by Zhiyuan-Amos** [comment]
Ah yes. Thanks for the reminder prof. Is having static ReadOnlyPerson ok? That way, it protects the state of these objects from being changed. If tests need to edit the fields, they need to use the Person constructor to construct a new Person object.

**Comment by damithc** [comment]
Yes, that might work.
