### ISSUE TITLE
PersonListPanel: Update scrollTo(int)

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#570]
PersonListPanel#scrollTo(int) calls Platform.runLater(Runnable) so that
the code within the lambda expression runs on the JavaFX thread.

Calling Platform.runLater(Runnable) is unnecessary as this method by
default runs on the JavaFX thread.

Let's remove the Platform.runLater(Runnable) call.

**Comment by yamgent** [comment]
> this method by
> default runs on the JavaFX thread.

Or rather all the codepath flow currently happens to run on JavaFX thread, so it is not necessary to use `Platform.runLater()`

**Comment by Zhiyuan-Amos** [comment]
I will close this issue because we have no guarantee that this method will only run on the JavaFX thread.
