### ISSUE TITLE
Lower the version number

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#575]
Shall we delete existing releases and do a new release under a lower version number. e.g. `v0.6`? That's because the next batch of students will take this version move towards v2.0; I want them to use v1.0, v1.1, .. v1.5 in their iterations.

**Comment by yamgent** [comment]
Should we wait until the `UndoCommand` and `RedoCommand` are merged before we release a new version?

**Comment by damithc** [comment]
Yes, not terribly urgent. As long as we do this before the start of the semester.

**Comment by Zhiyuan-Amos** [comment]
Also prof, is there a reason for `v0.6`? That's a pretty random number haha

**Comment by damithc** [comment]
> Also prof, is there a reason for v0.6? That's a pretty random number haha

That shows the product have already evolved over several minor versions already but has not reached 1.0
