### ISSUE TITLE
MainWindow: Remove Placeholders

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#577]
`MainWindow` consists of multiple placeholders. These placeholders act
as container view for the UI parts / View Controllers.

These placeholders are unnecessary. JavaFX provides simpler ways to
access sub-View Controllers that do not require us to maintain these
placeholders [1].

[1] See bullet point titled: Improved access to sub-controllers in FXML
http://docs.oracle.com/javafx/2/fxml_get_started/whats_new2.htm
Additional information:
https://stackoverflow.com/questions/9717852/how-to-pass-object-created-
in-fxml-controller1-to-controller2-of-inner-fxml-cont/10718683#10718683

**Comment by pyokagan** [comment]
@Zhiyuan-Amos Is this still really an issue?

**Comment by Zhiyuan-Amos** [comment]
Doesn't seem like it I guess; the current design is working fine. I'm not as familiar with FXML like you so I'll give it a pass :P
