### ISSUE TITLE
Developer Guide: suggest some micro enhancements to learn each component

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#579]
The DG should suggest some small enhancements for each component so that new developers (especially CS2103 students) has a way to get started on learning the code of each component.

**Comment by yamgent** [comment]
## `logic` component
* Add shorthand equivalent alias, which cannot be changed by the user (i.e. our official alias)

## `model` component
* Add a new `removeTag(Tag tag)` method. The specified tag will be removed from all persons, effectively removing it from the address book entirely too.

## `ui` component
* Use different colors for different tags.
* Modify `NewResultAvailableEvent` such that `ResultDisplay` can show a different style on error (right now it shows the same regardless of error or not).

## `storage` component
* Maybe convert the format for `UserPrefs` from `.json` to `.xml`????

**Comment by damithc** [comment]
Looks good. Perhaps we can add these under a `Getting Started in Writing Code` section in the dev guide?
