### ISSUE TITLE
Dev guide: suggest a new command to implement for beginners

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#581]
This feature does not have to be useful but should touch all components and should not be hard to implement.

**Comment by yamgent** [comment]
Do we need the level of difficulty to be the same for all components? I have an idea for a `remark` command but most work seems to be focused on the `Logic` component...

----

## `remark` Command
### Description
Edit the remarks for a person (could be quite long so maybe justifiable as a command by itself).

**Usage:** `remark <index> <remark>`

Example:
`remark 1 The quick brown fox jumps over the lazy dog.`.
* Changes the remark for the first person to `The quick brown fox jumps over the lazy dog.`

### Changes needed
#### Logic
* Add `RemarkCommand`
* Add `RemarkCommandParser`
* Modify `AddressBookParser`

#### Model
* Add `Remark`
* Modify `Person` to have a `Remark` field.

#### UI
* Connect the `Remark` field to show up in `PersonCard`.

#### Storage
* `XmlAdaptedPerson` now needs to store `Remark`.

**Comment by damithc** [comment]
> Do we need the level of difficulty to be the same for all components?

Ideally, but probably impossible, so it's ok for the difficulty to be different for different components.

The suggested `Remark` seems a good. May be do a quick implementation in your fork to see how? After that, we can include it in the dev guide, with some info on how to go about implementing it (i.e. a step-by-step guide)

**Comment by yamgent** [comment]
> May be do a quick implementation in your fork to see how? After that, we can include it in the dev guide, with some info on how to go about implementing it (i.e. a step-by-step guide)

Did a rough implementation here, seems feasible: https://github.com/yamgent/addressbook-level4/commits/prototype-dg-remark-command

**Comment by damithc** [comment]
Good work. Next step is to try to slice this into small increments that we can ask students to follow (if they can't figure out how to do it by themselves). e.g. 
1. teach the app to accept the `remark` command but do nothing
2. add a hard-coded remark to all person objects and teach the GUI to show it

Remind me to discuss this tomorrow.

**Comment by yamgent** [comment]
New branch:
https://github.com/yamgent/addressbook-level4/commits/prototype-round-2-remark

Each individual commit is a single step. @damithc
