### ISSUE TITLE
Add GuiTestAssert#assertListMatching(PersonListPanelHandle, List<ReadOnlyPerson>)

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level4#583]
Prerequisite: #573.

Some callers of `GuiTestAssert#assertListMatching(PersonListPanelHandle, ReadOnlyPerson...)` had to manually convert from a `List<ReadOnlyPerson>` to `ReadOnlyPerson[]` in order to conform with the method signature.

We can avoid the manual conversion by adding an overloaded helper method `GuiTestAssert#assertListMatching(PersonListPanelHandle, List<ReadOnlyPerson>)`:

```java

public static void assertListMatching(PersonListPanelHandle personListPanelHandle, List<ReadOnlyPerson> persons)
        throws PersonNotFoundException {
    assertListMatching(personListPanelHandle, persons.toArray(new ReadOnlyPerson[persons.size()]));
}
```

**Comment by Zhiyuan-Amos** [comment]
Closing this issue because I can't find this issue in the code base anymore :)

**Comment by yamgent** [comment]
That's because you added that method in 0126a8a1f78b6122ca7936fda6fde7ac79cc61ac already.
