### ISSUE TITLE
Create a fake PR containing all code related to undo/redo

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#609]
Create a new branch from a point before adding the feature.
Cherrypick all relevant commits to new branch.
Create (and close) a PR for that branch.

**Comment by yamgent** [comment]
Fake PR is here: https://github.com/se-edu/addressbook-level4/pull/610.

**Comment by damithc** [comment]
Should also contain recent dev guide commits that explains the implementation of the feature?

**Comment by yamgent** [comment]
@damithc added. Does it look ok now?

**Comment by damithc** [comment]
Yup. 👍
