### ISSUE TITLE
CommandBox: rename method handleCommandInputChanged()

### ISSUE THREAD

**Issue by eugenepeh** [se-edu/addressbook-level4#629]
`handleCommandInputChanged()` method name sounds misleading since this event only triggers when user press the "Enter" button and not every time when user types something. We should rename it to something that match what it is doing. E.g. `handleCommandEntered()`.

**Comment by Zhiyuan-Amos** [comment]
Whoever is resolving this issue in the future and is unfamiliar with FXML, you will have to update the method name in `CommandBox.java` and update the `onAction`'s attribute value in `CommandBox.fxml`. ^^
