### ISSUE TITLE
UniquePersonList: Update setPersons(...) parameter

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#633]
```
setPersons(List<? extends ReadOnlyPerson>) throws 
DuplicatePersonException. This method is only called by 
AddressBook#setPersons(List<? extends ReadOnlyPerson>).

This results in AddressBook#resetData(ReadOnlyAddressBook) having to 
handle the DuplicatePersonException by asserting false since this 
should not happen (resetData(ReadOnlyAddressBook) calls 
setPersons(List<? extends ReadOnlyPerson>)).

Let's update the method signature to 
setPersons(Set<? extends ReadOnlyPerson>) so that this method does not
throw DuplicatePersonException, and 
AddressBook#resetData(ReadOnlyAddressBook) does not have to handle it.
```

**Comment by Zhiyuan-Amos** [comment]
@yamgent can validate issue? Thanks ^^

**Comment by yamgent** [comment]
I have no problems with changing the parameter to `Set`, just need to make sure that `Person`'s hash code is thoroughly tested.

**Comment by Zhiyuan-Amos** [comment]
Why does `Person`'s hash code need to be thoroughly tested?

**Comment by yamgent** [comment]
That is how the `Set` class works. It uses `getHashCode()` to determine uniqueness, otherwise you can create two different objects with the same particulars and they will still report unique if `getHashCode()` is not implemented.

**Comment by Zhiyuan-Amos** [comment]
@yamgent I'm rethinking about this issue because a `Set` is unordered, as such, callers will not know the order of the `AddressBook` when calling `setPersons(Set<? extends ReadOnlyPerson>)`.

As such, I'm thinking that we should just close this issue and leave the code as it is.

**Comment by yamgent** [comment]
Yeah, I think the order in the data structure is quite important. Agree that we should close it.
