### ISSUE TITLE
Checkstyle errors

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#646]
The diagram below shows a method in `GuiRobot`

![image](https://user-images.githubusercontent.com/19281514/29762033-d36a9c52-8bfe-11e7-8caf-b3a5b56cd852.png)

The `@throws` tag is highlighted red. Upon hovering over it, there's an error message stating that "Checkstyle is unable to get class information of the tag". The error message will disappear if we add the `EventTimeoutException` as part of the throws clause of the method declaration, but we shouldn't do so because `EventTimeoutException` is a `RunTimeException`.

**Comment by eugenepeh** [comment]
Hi @Zhiyuan-Amos , I'm unable to replicate this error 
![image](https://user-images.githubusercontent.com/19277206/30406737-3b0d7e36-9926-11e7-8138-c507339d26af.png)

Did you do anything special prior to seeing this?

**Comment by Zhiyuan-Amos** [comment]
Yup seems like the error has been resolved ^^ I didn't do anything special though; previously it was highlighted red on my IntelliJ, but it didn't cause the build to fail (which is kinda weird right?)
