### ISSUE TITLE
Remove UnmodifiableObservableList

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#649]
JavaFX has a class ~~ReadOnlyListPropertyBase<E>~~ `ReadOnlyListWrapper<E>` which works similar to `UnmodifiableObservableList`.

**Comment by Zhiyuan-Amos** [comment]
@damithc need your verification on this because I think @yamgent and myself weren't around yet when this class was implemented ^^

**Comment by damithc** [comment]
@AlexLMeow is the one who might be able to give some input on this.

**Comment by Zhiyuan-Amos** [comment]
We will remove 300 lines from our main code base if we do so (it's irresistible isn't it :P)

On a side note, in `DeleteCommand#executeUndoableCommand()`, there's this line of code:
`UnmodifiableObservableList<ReadOnlyPerson> lastShownList = model.getFilteredPersonList();`

Even though `model#getFilteredPersonList()` returns a `UnmodifiableObservableList`, I wonder whether there's a need to make `lastShownList` a `UnmodifiableObservableList`. As far as `DeleteCommand` is concerned, it seems like what it needs is just a `List`.

**Comment by yamgent** [comment]
> As far as DeleteCommand is concerned, it seems like what it needs is just a List.

As long as the `List` is a defensive copy of the internal list then I think it is fine. Generally the model should be the one concerned with deleting/modifying the person, so if `Command`s can directly modify the person's field on their own this breaks both Law of Demeter and the Facade pattern.

**Comment by Zhiyuan-Amos** [comment]
> As long as the List is a defensive copy of the internal list 

It isn't a defensive copy, though it is an unmodifiable version of the original list. Same as the way we are working with `Person` and `ReadOnlyPerson`.
