### ISSUE TITLE
ReadOnlyPerson: Change implementation

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#651]
`ReadOnlyPerson` can easily be casted back to `Person`, causing it to lose the read-only properties. 

![image](https://user-images.githubusercontent.com/19281514/29931324-7dcc2d18-8ea3-11e7-9558-2869524bc296.png)

Having spent a while looking at Java API, there are multiple occasions when the API returns the original type even though it explicitly states that the returned object is unmodifiable (e.g. in the image above, the return type is `ObservableList` and not something like `ReadOnlyListWrapper`). 

As such, I'm wondering whether we can have `ReadOnlyPerson` to subclass `Person`, and we can override the setter methods to throw a `RunTimeException`. That way, in getter methods like `UniquePersonList#asObservableList()`
```
public UnmodifiableObservableList<Person> asObservableList() {
    return new UnmodifiableObservableList<>(internalList);
}
```
Though the type of the list is `Person`, but more specifically it is of type `ReadOnlyPerson`. Then we can add header comments to mention that both the list and the `Person` objects inside the list are unmodifiable. This resolves the problem mentioned in the first paragraph.

-----------

Alternatively, we can make `Person` immutable by removing the setter methods. We don't use them in the main code base except for `setTags`.

**Comment by Zhiyuan-Amos** [comment]
@yamgent thoughts ^^

**Comment by damithc** [comment]
> As such, I'm wondering whether we can have ReadOnlyPerson to subclass Person, and we can override the setter methods to throw a RunTimeException. That way, in getter methods like UniquePersonList#asObservableList()

That would violate the Liskov Substitution Principle

**Comment by yamgent** [comment]
As Prof mentioned, such change would lead to violation of LSP.

If we want to prevent programmer abuse, maybe such methods should return a defensive copy, so that the original copy is not modified?

**Comment by Zhiyuan-Amos** [comment]
> maybe such methods should return a defensive copy

`UniquePersonList` has to return the list as it is because the UI observes the list. If a defensive copy is being returned, what happens is that in the event that a `Person`'s details are being edited in the original list (though we can't do that now because there's no API exposed by `UniquePersonList`), then the UI won't be notified of the change because it has a defensive copy.

> That would violate the Liskov Substitution Principle

I agree that this violates LSP. I'm trying to think of how Java API implements it internally, because in the image that I've attached above, an `ObservableList` is returned instead of some other type like `UnmodifiableObservableList` etc, and operations such as `add` are disabled (i.e. upon method call, an Exception is thrown).

As such, I'm thinking of having `ReadOnlyPerson` subclassing `Person`, but we never expose the idea of a `ReadOnlyPerson` to the rest of the code base. I.e. getter methods such as `asObservableList()` in `UniquePersonList` will still return a type `Person` to callers, but upon calling `setName` etc, an Exception will be thrown.

**Comment by Zhiyuan-Amos** [comment]
https://netopyr.com/2012/02/02/creating-read-only-properties-in-javafx/

Can refer to Listing 3. ^^
