### ISSUE TITLE
UniquePersonList#iterator() should return Iterator<ReadOnlyPerson>

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#653]
`UniquePersonList#iterator()` returns `Iterator<Person>`. 

Callers can update the values of the `Person` objects, possibly violating the uniqueness of the `Person` objects in `UniquePersonList`.

**Comment by Zhiyuan-Amos** [comment]
@yamgent issue validation pls ^^

**Comment by yamgent** [comment]
Ok
