### ISSUE TITLE
README/Contributors: refer to se-edu instead of listing here

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#660]
Change the Contributors section similar to level2

**Comment by Zhiyuan-Amos** [comment]
@damithc issue validation, because I recall using the `About Us` page in CS2101 (I can't quite recall though).

**Comment by damithc** [comment]
Yes, it is used by CS2103.
We can structure is like this:
Add this at the top.
> The product was developed by the [se-edu] team. The content below is a placeholder for future forks of the project.

Change names to place holder names e.g. John Doe etc.
Remove the `Contributors` section at the bottom.
