### ISSUE TITLE
Decouple UndoableCommand from ReadOnlyAddressBook

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#670]
`UndoableCommand` stores the state of the `AddressBook` before the command was executed.

This is unnecessary coupling.

We can decouple it by either:
1. Using the `Memento` pattern. https://www.tutorialspoint.com/design_pattern/memento_pattern.htm, which I think is somewhat similar to using undoStack/redoStack to store the states instead of storing the commands.
2. Updating `UndoableCommand` to undo each command by taking logical steps. Just a quick thought: This seems impossible without storing some information of the current state as well. For e.g. `DeleteCommand` would require adding the person back into the `AddressBook`.

**Comment by damithc** [comment]
While it's good to record this possible improvements, we should not actually implement them unless they make the code simpler. Otherwise we could end up complicating the code beyond an average _SE beginner_ student.

**Comment by Zhiyuan-Amos** [comment]
Yup, I think that this can make the code simpler.

1. Remove `UndoableCommand`. All `Command`s have to implement `boolean isUndoable()`.
2. `UndoRedoStack` no longer stores commands, but they store the states of the `AddressBook`. 

That way, we decouple `AddressBook` from `UndoableCommand`. We don't have to use `Memento` pattern if it looks complicated.

**Comment by pyokagan** [comment]
@Zhiyuan-Amos 
> Yup, I think that this can make the code simpler.
>
> 1. Remove `UndoableCommand`. All `Command`s have to implement `boolean isUndoable()`.
> 2. `UndoRedoStack` no longer stores commands, but they store the states of the `AddressBook`. 
>
> That way, we decouple `AddressBook` from `UndoableCommand`. 

I like this idea btw, small and simple. Might help resolve #828
