### ISSUE TITLE
SampleDataTest: Fix buggy implementation of getDataFileLocation()

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#678]
getDataFileLocation() must return a non-existent file location as part
of this method's post-condition.

However, this isn't ensured in the current implementation. As a result,
the test case in SampleDataTest may fail.

Let's update getDataFileLocation() to ensure that it returns a 
non-existent file location.

**Comment by damithc** [comment]
How likely it is for this to happen? And if it happens, what is the consequence? If it is rare coincidence and if it results in a test failure, then perhaps we don't need to do anything?

**Comment by Zhiyuan-Amos** [comment]
I noticed it when I was running all tests on my Mac, while trying to fix #675 :P
