### ISSUE TITLE
Upgrade to Java 9

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#681]
Java 9 ~~will be released on 21st September~~ is released! 

Some changes that we can look into:
1. Convert method calls like `Arrays#asList(...)` to use `List#of(...)`.  https://dzone.com/articles/java-9-factory-methods-to-create-immutable-collect
1. Look into using `Runtime.Version`. https://dzone.com/articles/process-api-and-version-in-java-9

**Comment by Zhiyuan-Amos** [comment]
@damithc Can we upgrade the code base to Java 9? This fixes #374 too.

**Comment by damithc** [comment]
I guess we can, as long as we do that quickly, before students start on level 4.

**Comment by Zhiyuan-Amos** [comment]
@yamidark take a look at what I've done so far for [Java 9](https://github.com/Zhiyuan-Amos/addressbook-level4/tree/java9) on my branch.

**Comment by damithc** [comment]
It's too late for this sem but we have to make the project Java 9 compatible by next sem. I thought there is no hurry because Java is normally backward compatible but apparently AB4 runs into issues in Java 9 environments.

**Comment by Zhiyuan-Amos** [comment]
Ah I see; I thought students were still using Java 8. I'll look into it.

**Comment by damithc** [comment]
> I thought students were still using Java 8.

CS2030 uses Java 9; that's why some students are already on Java 9 when they come to CS2103. In any case, we should ensure _compatibility_ with the latest public version as soon as it is out (but we can wait a while before we make the latest version a  _prerequisite_)

**Comment by pyokagan** [comment]
@Zhiyuan-Amos 
> Convert method calls like Arrays#asList(...) to use List#of(...). https://dzone.com/articles/java-9-factory-methods-to-create-immutable-collect
> Look into using Runtime.Version. https://dzone.com/articles/process-api-and-version-in-java-9

Can split this into separate issues? I guess they will be lower priority as well (and maybe first-timers?)

I think this issue, as it is, has been resolved and can be closed.

**Comment by Zhiyuan-Amos** [comment]
@pyokagan noted.

Closing this issue, for other updates that we can make to our codebase, see #871 and #872.
