### ISSUE TITLE
DeveloperGuide: Update header numbering

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#682]
There's `3.1.1. Design Considerations`, but there isn't `3.1.2.`

Edit:
We can rename `3.1. Undo/Redo mechanism` to `3.1. Undo/Redo`, followed by a `3.1.1. Mechanism` and `3.1.2. Design Considerations`.

Also, I recall learning from either CS2101 or CS2103 that we shouldn't have a `.1` if there isn't a `.2`. Can't find the notes now though.

**Comment by pyokagan** [comment]
@Zhiyuan-Amos 
> There's 3.1.1. Design Considerations, but there isn't 3.1.2. This perhaps implies that we don't need to have a 3.1.1..

What does this mean? The numbering should be `3.1` (which will clash with the level 2 "Undo/Redo mechanism" heading above)? There should not be any numbering?

Anyway, the numbering is automatic, and the number of dots is meant to show the reader what level the heading is at. (i.e. `3.1.1` means a level 3 heading, aka it is a subsection of section 3.1). This kind of header numbering is quite standard, so I don't think this is an issue.

**Comment by Zhiyuan-Amos** [comment]
> What does this mean? The numbering should be 3.1 (which will clash with the level 2 "Undo/Redo mechanism" heading above)? There should not be any numbering?

Apologies for being unclear; initially I wasn't quite sure myself of how to resolve this. I recall learning from either CS2101 or CS2103 that we shouldn't have a `.1` if there isn't a `.2`.

What do you think of renaming `3.1. Undo/Redo mechanism` to `3.1. Undo/Redo`, followed by a `3.1.1. Mechanism` and `3.1.2. Design Considerations`?

**Comment by pyokagan** [comment]
@Zhiyuan-Amos 
> What do you think of renaming 3.1. Undo/Redo mechanism to 3.1. Undo/Redo, followed by a 3.1.1. Mechanism and 3.1.2. Design Considerations?

I don't mind. You should submit a PR for these kind of things though, other people won't usually take up these kind of issues :-)

**Comment by Zhiyuan-Amos** [comment]
@pyokagan 

Noted, thanks for making me think deeper ^^

@damithc 

Do you think that I should make this small change?

**Comment by damithc** [comment]
> Do you think that I should make this small change?

Sure. go ahead.
