### ISSUE TITLE
Guitests: Move tests to other packages

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#684]
1. `HelpWindowTest` looks like it can be renamed to `HelpCommandTest` and moved to `systemtests`.
1. `ErrorDialogGuiTest` and `SampleDataTest` can be shifted to `systemtests` as well. 
1. `StatusBarFooterTest` is superseded and can be removed as we now have system tests.

This is because `AddressBookGuiTest` and `AddressBookSystemTest` are very similar classes.

**Comment by Zhiyuan-Amos** [comment]
@damithc your thoughts, cos this relates to updating the DeveloperGuide in #683

**Comment by damithc** [comment]
Go ahead, if you can do it quickly.
