### ISSUE TITLE
Checkstyle-IDEA shows error: Unable to get class information

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#687]
Probably not critical, but nice if we can avoid it
![image](https://user-images.githubusercontent.com/1673303/30574304-98f1bf68-9d2b-11e7-8333-8827d2f5fc5b.png)

**Comment by Zhiyuan-Amos** [comment]
@eugenepeh on a side note, I can't even configure checkstyle actually (I just realized) :O 

Tried the solution here but it doesn't work. https://github.com/se-edu/addressbook-level4/blob/master/docs/DeveloperGuide.adoc#14-troubleshooting-checkstyle-idea

**Comment by damithc** [comment]
What's the error you are getting?

**Comment by Zhiyuan-Amos** [comment]
The 1st problem in 1.4

**Comment by damithc** [comment]
I had the same problem but it went away after selecting the right version.
Did you install the plugin just now or was it a previous install? If the latter, try uninstalling the plugin and installing again (if you haven't done that already).

**Comment by Zhiyuan-Amos** [comment]
Tried reinstalling the plugin, and I chose the correct version (8.1), but it still doesn't work :<

**Comment by eugenepeh** [comment]
> Probably not critical, but nice if we can avoid it

Think the error is when there's throw tag but no explicit throw exception

> The 1st problem in 1.4

Did the IDE prompt anything after 60s? Sometimes it shows the error when you spam execute the checkstyle 

Or can you try to see if it works on master branch?

**Comment by damithc** [comment]
Seems like a temporary problem. I don't get that error anymore. CheckStyle plugin seems a bit buggy :-p

**Comment by Zhiyuan-Amos** [comment]
> Did the IDE prompt anything after 60s? Sometimes it shows the error when you spam execute the checkstyle

I removed it and tried importing it, but it failed to import, with the error in 1.4 :(

> Or can you try to see if it works on master branch?

Doesn't work here either!

**Comment by eugenepeh** [comment]
😱 are you using Mac??

**Comment by Zhiyuan-Amos** [comment]
> 😱 are you using Mac??

Yes! :O

**Comment by eugenepeh** [comment]
hmm... are you able to run checkstyle using gradle?

**Comment by Zhiyuan-Amos** [comment]
Yup. It fails if I violate checkstyle rules (like unused import). The thing is I didn't choose any checkstyle configuration file though.

![image](https://user-images.githubusercontent.com/19281514/30597064-759cac00-9d88-11e7-9f07-81045b8fbf01.png)

**Comment by eugenepeh** [comment]
hmm... strange... maybe mac ide bug... i not sure cus i using windows 

btw i mean gradle using terminal xD

**Comment by Zhiyuan-Amos** [comment]
Tried using terminal, works too. LOL.

**Comment by eugenepeh** [comment]
hmm, final solution, try updating IDE? xD

**Comment by Zhiyuan-Amos** [comment]
> hmm, final solution, try updating IDE? xD

It's alrd updated. :P I guess the final solution is... To stop coding for AddressBook. :P HAHA

**Comment by eugenepeh** [comment]
Hahaha, it's okay I believe your coding standard is good enough to pass the checkstyle test 😝
