### ISSUE TITLE
Tweaks to User Guide

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#698]
![image](https://user-images.githubusercontent.com/1673303/30672316-5753d9e6-9e9e-11e7-9a04-b38af8827439.png)
This link is broken

----

Tweak as follows:
>* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add n/NAME`, `NAME` is a parameter which can be used as `add n/John Doe`
>* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used as `n/John Doe t/friend` or as `n/John Doe`.
> * Items with `…​` after them can be used multiple times including zero times e.g. `[t/TAG]...` can be used as ` ` (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
> * Parameters can be in any order e.g. if the command specifies `n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable.

----

![image](https://user-images.githubusercontent.com/1673303/30672632-3b1e9f2a-9ea0-11e7-91a0-3ba3a66e01fe.png)

1. Title can be shortened to `Locating persons by name`
2. This example is not clear. Can be,
>`Hans Bo` will return `Hans Gruber`, `Bo Yang`
3. This example is not consistent with the claim that the `find` is case insensitive

----

![image](https://user-images.githubusercontent.com/1673303/30672725-c2b3a3d6-9ea0-11e7-8e8d-17d6f6ae544c.png)

Should be `Selecting a person`

----

![image](https://user-images.githubusercontent.com/1673303/30672807-361e04f6-9ea1-11e7-84bf-a61d526c66d1.png)
Numbers should be in code formatting?

----

![image](https://user-images.githubusercontent.com/1673303/30672828-6463686a-9ea1-11e7-8de0-abba28d20da4.png)
Should be `Undoing` (to be consistent). Same for `Redo`.

----

![image](https://user-images.githubusercontent.com/1673303/30672852-a17b8462-9ea1-11e7-8517-baf43b2987d8.png)
`A person can ...`?

**Comment by damithc** [comment]
@Zhiyuan-Amos can do this one?

**Comment by Zhiyuan-Amos** [comment]
> This link is broken

The link works for me though.

> This example is not consistent with the claim that the find is case insensitive

There's an example (`The search is case insensitive. e.g hans will match Hans`) which explains this claim. Sorry which part are you referring to? ><

**Comment by damithc** [comment]
> The link works for me though.

It works in the .adoc version but not in the [html version](https://se-edu.github.io/addressbook-level4/UserGuide.html)

>There's an example (The search is case insensitive. e.g hans will match Hans) which explains this claim. Sorry which part are you referring to?

Sorry, I meant to refer to this example (which suggests the `find` is case sensitive) instead.
![image](https://user-images.githubusercontent.com/1673303/30695166-bdbf9902-9f09-11e7-99cb-100b326df5bd.png)

**Comment by Zhiyuan-Amos** [comment]
> It works in the .adoc version but not in the html version

Ah yes ok! How should I resolve this though? That's because there isn't an offline version of `releases`. ><

> Sorry, I meant to refer to this example (which suggests the find is case sensitive) instead.

Ah didn't see the arrow, my bad!

**Comment by damithc** [comment]
> Ah yes ok! How should I resolve this though? That's because there isn't an offline version of releases.

Hardcode the full url?
