### ISSUE TITLE
Storage should not extend from AddressBookStorage and UserPrefsStorage

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#711]
```
Storage interface extends AddressBookStorage and UserPrefsStorage. As 
such, Storage is forced to implement methods such as 
readAddressBook(String filePath).

This unnecessarily couples Storage with these other components, which 
causes Storage to implement unnecessary methods like 
readAddressBook(String filePath). Other components of the program have
no need to retrieve an address book from other file paths.

Let's update Storage to no longer extend from AddressBookStorage and
UserPrefsStorage, and delete unnecessary methods such as 
readAddressBook(String filePath).
```

**Comment by Zhiyuan-Amos** [comment]
@yamgent, I think you were mentioning something along this line in #708? Let me know if you think that this is good, that way I can update #708 accordingly. I will post a comment shortly on that issue.

**Comment by yamgent** [comment]
Yes that is correct, I find it quite weird for `Storage` to be extending `AddressBookStorage` and `UserPrefsStorage`, since it is meant to be a facade for general storage management API (i.e. a `StorageManager`), rather than it being an actual address book/user pref storage class.

**Comment by damithc** [comment]
`Storage implements AddressBookStorage, UserPrefsStorage` is an application of the interface segregation principle. As such, `Storage` is not general _read/write anything_ type low level persistence class. It is aware of what it is storing, namely, AddressBook objects and UserPrefs objects. Furthermore, a client that deals with AddressBook objects but not UserPrefs objects can use Storage via the AddressBookStorage interface (i.e. not forced to know methods that it doesn't need). Anyway, that was the original intention but not sure if the code actually benefit from ISP. I'm not opposed to a redesign.

**Comment by pyokagan** [comment]
@Zhiyuan-Amos @yamgent Can we reboot this conversation to determine if (1) this is indeed a big enough issue (after the counterpoint from @damithc ), and if yes (2) I think you can just submit a PR for this directly since this would be a simple enough change?

**Comment by yamgent** [comment]
I think we can all agree that we are trying to showcase ISP for this part of the code.

The main problem I had with this design was that the context switch is very abrupt and strange. A `Manager` can suddenly become **not** a `Manager`:

```java
// a generic manager is treated as just an address book storage (???!?!)
AddressBookStorage addressBookStorage = (AddressBookStorage)storageManager;

...

Path path = addressBookStorage.getAddressBookFilePath();
```

Whereas I would have thought that it staying as a manager would have make more sense:

```java 
// a generic manager is treated as an address book manager
// ISP still applies in this case, we do not need UserPrefs stuff so we "got rid" of them
AddressBookStorageManager addressBookStorageManager = (AddressBookStorageManager)storageManager;

...

Path path = addressBookStorageManager.getAddressBookFilePath();
```

**Comment by yamgent** [comment]
I realised that I didn't really present it very well on the previous post (I spent 30+ minutes on it :P), so here's an addendum:

`XmlAddressBookStorage` also implements `AddressBookStorage`. So, is `XmlAddressBookStorage` a manager?

* If yes, does it mean that it should be renamed to `XmlAddressBookStorageManager`?
* If no, then `AddressBookStorage` is implemented by both a manager and a **non**-manager. This seems like a contradiction?

**Comment by yamgent** [comment]
After a day of thinking, I can summarize my entire point in one sentence: One single interface has multiple semantic meaning at the same time, whereas usually an interface is consistent in what it represents, even if there are different implementation of it.

However, I must admit that my argument is weak because I did not provide a solution to solve this problem, which will probably require some sort of redesign.

If it is still a concern in the future, perhaps someone will give a better idea on what is going on. Meanwhile I think we can close the issue because I can't propose a solution to this problem atm.
