### ISSUE TITLE
import static seedu.address.testutil.TypicalPersons.KEYWORD_MATCHING_MEIER;

### ISSUE THREAD

**Issue by chilipadiboy** [se-edu/addressbook-level4#713]
KEYWORD_MATCHING_MEIER 

does not exist in Typical Persons anymore. However it is still being used in the ClearCommandSystemTest.java

**Comment by chilipadiboy** [comment]
It should be from TypicalIndexes

**Comment by Zhiyuan-Amos** [comment]
![image](https://user-images.githubusercontent.com/19281514/31159005-653b45d0-a8f8-11e7-9689-de30052920c0.png)

It exists in `TypicalPersons` on my side :P Can you verify again @chilipadiboy
