### ISSUE TITLE
DeveloperGuide#A.1.: following PR solution fails the checkstyleTest

### ISSUE THREAD

**Issue by eugenepeh** [se-edu/addressbook-level4#724]
This is one of the feedback pointed out by the students during tutorial,

Under the [DeveloperGuide#A.1.](https://github.com/se-edu/addressbook-level4/blob/master/docs/DeveloperGuide.adoc#a1-improving-each-component) -> Storage component -> See this [PR](https://github.com/se-edu/addressbook-level4/pull/594/files) for the full solution.

The students followed the PR solution but failed the checkstyleTest as the solution code does not meet the `OverloadMethodsDeclarationOrder` check requirement.

**Comment by damithc** [comment]
To be fixed before next semester (we should refine all those sample PRs; they were created in a rush -- my bad for rushing it; and may have become outdated in other places too).

**Comment by Zhiyuan-Amos** [comment]
Should be resolved now since the CI tests are passing in https://github.com/se-edu/addressbook-level4/pull/594
