### ISSUE TITLE
HelpWindow: May interfere with UI Components while active

### ISSUE THREAD

**Issue by karrui** [se-edu/addressbook-level4#727]
Discovered this while testing other applications, the commands fail to show if the help window is open in the background.
Refer to: https://github.com/CS2103AUG2017-W14-B4/main/issues/106

`exit` command is blocked from executing while help window is open too.

Steps to reproduce:
1. Open help window
2a. Enter any command
Command result messages fail to display to user.
Use case end.

2b. Type `exit`
Application will not exit until help window is closed
Use case end

Normally closing the application by using the mouse will still close the application

Edit by Zhi Yuan: See https://github.com/nus-cs2103-AY1718S1/forum/issues/181#issuecomment-341664086 as well

**Comment by liuhang0213** [comment]
Observed similar behaviour in our own application and the one I am testing. The outputs are redirected to the terminal instead of being displayed in the address book command result box.

**Comment by Zhiyuan-Amos** [comment]
Great catch ^^

**Comment by conantteo** [comment]
Hi,
With regards to this issue, I think it is because of the method [stage.showAndWait()](https://docs.oracle.com/javase/8/javafx/api/javafx/stage/Stage.html#showAndWait--)

Would a workaround be using stage.show() instead so that it does not interfere with the MainWindow?
Tested by typing help in commandBox followed by other commands before exit in commandBox.

**Comment by Zhiyuan-Amos** [comment]
Yup I'm guessing that the `showAndWait()` may affect it, though I'm not sure why Pressing F1 / Clicking on the Help button doesn't cause the issue (the issue only occurs when you enter `help` in the Command Box). 

But sure, a quick fix will be to simply use `show()`. I recall doing so as well when I was taking CS2103. ^^ Perhaps Prof @damithc knows about why `showAndWait()` was used in the first place?

**Comment by damithc** [comment]
> Perhaps Prof @damithc knows about why showAndWait() was used in the first place?

No idea. Probably not a conscious choice. :-p
