### ISSUE TITLE
LogicManager: constructor does not follow coding standard's usage of 'this'

### ISSUE THREAD

**Issue by PierceAndy** [se-edu/addressbook-level4#729]
`LogicManager`'s constructor currently looks like this:
```
public LogicManager(Model model) {
        this.model = model;
        this.history = new CommandHistory();
        this.addressBookParser = new AddressBookParser();
        this.undoRedoStack = new UndoRedoStack();
}
```

This goes against [our coding standard](https://github.com/oss-generic/process/blob/master/codingStandards/CodingStandard-Java.adoc#variables):
![image](https://user-images.githubusercontent.com/8639005/32419991-efa8e33c-c2be-11e7-8b1f-e43d9ecdbccf.png)

**Comment by damithc** [comment]
Yes, `this.model = model;` is fine but `this` is unnecessary in the remaining three lines
