### ISSUE TITLE
Some tests can fail on Travis if Google rejects search requests

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#733]
Some tests depend on being able to load the Google search page. These tests can fail if Google rejects the search request on account of too many search requests being issued from Travis servers. In fact I worry that this might even affect other users on Travis :-p

**Comment by Zhiyuan-Amos** [comment]
I guess this can't be helped since the part of the requirement of system tests is to verify that the browser loads? ><

**Comment by damithc** [comment]
Let's fix this before the next batch starts because it can cause frustrations to students.
