### ISSUE TITLE
Email regex validation does not accept `+`

### ISSUE THREAD

**Issue by derrickchua** [se-edu/addressbook-level4#743]
It was posted as one of our bugs that the email address validation is not entirely correct, as certain characters such as "+" are not accepted, even though they are valid. More details can be found [here](https://github.com/nus-cs2103-AY1718S1/pe-results/issues/42) .

**Comment by vivekscl** [comment]
Regarding this issue, there are other valid characters other than "+'' that are not accepted as stated in [Wikipedia](https://en.wikipedia.org/wiki/Email_address#Local-part) such as `!#$%&'*+-/=?^_{|}~`. Furthermore, the current email validation regex accepts invalid characters such as full stops in the local part without being encapsulated in the quotes. Should we change those as well and all in one PR?

**Comment by damithc** [comment]
Is there any universally accepted regex that can do email validation?
If there is no such, it is better to accept invalid inputs (user is partially to blame for these) rather than reject valid inputs (the fault is entirely of the app).  i.e., too loose validation is better than too tight.

**Comment by vivekscl** [comment]
There is a universally accepted regex that follows the RFC5322 format, which is as follows:
^[a-zA-Z0-9_!#$%&’*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$
There are more restrictive forms such as restricting trailing and consecutive full stops but as you said, it is better to have a loose validation than a tighter one.
[Link to the regex](https://howtodoinjava.com/regex/java-regex-validate-email-address/)
