### ISSUE TITLE
"123" is accepted as a valid address

### ISSUE THREAD

**Issue by chernghann** [se-edu/addressbook-level4#744]
One of our bugs was on the check for valid address. We used the code from AB4 Address.java and did not make any changes. More details found [here](https://github.com/nus-cs2103-AY1718S1/pe-results/issues/974)

**Comment by damithc** [comment]
Different countries have different address formats. Also, users don't always have the full address of a contact. So, I'm not sure if it is a good idea to apply stricter validation on the address field, unless the target usage of the app is redefined to require a specific address format.

**Comment by pyokagan** [comment]
@chernghann 
> One of our bugs was on the check for valid address. We used the code from AB4 Address.java and did not make any changes. More details found here

What's the full context of this issue? I can't access the link.

**Comment by chernghann** [comment]
Our reviewers felt that there should be a validation for the address. From the image that they have attached, they have input "123" as an address and hence marked it as a bug since 123 is not a valid address.
