### ISSUE TITLE
AddressBook needs to track tags properly

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#753]
https://github.com/se-edu/addressbook-level4/blob/edc42f0e2579c27c209b1f8f3c0f87ed04e83904/src/main/java/seedu/address/model/AddressBook.java#L89-L91

https://github.com/se-edu/addressbook-level4/blob/edc42f0e2579c27c209b1f8f3c0f87ed04e83904/src/main/java/seedu/address/model/AddressBook.java#L111-L113

There's also the issue that tags are not removed once the last person using that tag is removed from the address book (i.e. the set of tags will just keep growing :-P)

The tag list is also actually not used at all. We should either find some use for it, or remove it.

**Comment by damithc** [comment]
IIRC, the original intention was to have only one instance of each tag as a list of `Tag` objects and all `Person` objects should point to the relevant tags in the list, instead of keeping its own copy. That way, we just need to modify one Tag object when a Tag is edited.

**Comment by Zhiyuan-Amos** [comment]
> That way, we just need to modify one Tag object when a Tag is edited.

`Tag` is immutable though :P Also, we don't have a tag renaming feature.

**Comment by damithc** [comment]
> Tag is immutable though :P Also, we don't have a tag renaming feature
Tag renaming is one of the common extensions students do. Also, another possible extension is the ability to set/change color of a tag. As an OOP solution, we should treat tags as an object that is referenced by multiple other objects rather than a value that is being copied to multiple other objects?

**Comment by pyokagan** [comment]
@damithc 

> As an OOP solution, we should treat tags as an object that is referenced by multiple other objects rather than a value that is being copied to multiple other objects?

I dunno, I wonder if students in the CS2103 level still have trouble with pointers. Even some SE-EDU developers in the past had trouble deciphering the intent of `syncMasterTagListWith`

**Comment by damithc** [comment]
How about we do it the simple way (i.e., no independent tag list) and give the other approach as a 'more OOP' alternative in the dev guide?

**Comment by Zhiyuan-Amos** [comment]
As discussed [here](https://github.com/se-edu/addressbook-level4/pull/794#issuecomment-360468923), we will be removing `UniqueTagList`.
