### ISSUE TITLE
Explore adapting AB4 to use a chat interface

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#757]
A CLI interface is very close to a chat interfaces but the latter sounds more 'modern'. Perhaps adapting our command box component to work like a chat interface might make AB4 experience more _marketable_ (e.g. when students apply for internships/jobs)?

**Comment by pyokagan** [comment]
@damithc Now that the chat bot fad (:stuck_out_tongue: ) is over, this seems like it won't really help. Perhaps we should just close this issue?

**Comment by damithc** [comment]
> @damithc Now that the chat bot fad (😛 ) is over, this seems like it won't really help. Perhaps we should just close this issue?

Sure.
