### ISSUE TITLE
JUnit5: Shorten test code by using parameterized tests

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#786]
If we use JUnit 5 instead (#707), we can use new annotations to make some of our tests more readable. For example, in `AddCommandParserTest`, we have quite a bit of boilerplate code as we have multiple `assertParseFailure(...)`. Existing code:

```java
@Test
public void parse_compulsoryFieldMissing_failure() {
    String expectedMessage = String.format(MESSAGE_INVALID_COMMAND_FORMAT, AddCommand.MESSAGE_USAGE);

    // missing name prefix
    assertParseFailure(parser, VALID_NAME_BOB + PHONE_DESC_BOB + EMAIL_DESC_BOB + ADDRESS_DESC_BOB,
            expectedMessage);

    // missing phone prefix
    assertParseFailure(parser, NAME_DESC_BOB + VALID_PHONE_BOB + EMAIL_DESC_BOB + ADDRESS_DESC_BOB,
            expectedMessage);

    // missing email prefix
    assertParseFailure(parser, NAME_DESC_BOB + PHONE_DESC_BOB + VALID_EMAIL_BOB + ADDRESS_DESC_BOB,
            expectedMessage);

    // missing address prefix
    assertParseFailure(parser, NAME_DESC_BOB + PHONE_DESC_BOB + EMAIL_DESC_BOB + VALID_ADDRESS_BOB,
            expectedMessage);

    // all prefixes missing
    assertParseFailure(parser, VALID_NAME_BOB + VALID_PHONE_BOB + VALID_EMAIL_BOB + VALID_ADDRESS_BOB,
            expectedMessage);
}
```

However, when we use the new annotations in JUnit 5, we can supply the parameters outside of the test method, thus we only have one `assertParseFailure(...)`.

```java
@ParameterizedTest
@ValueSource(strings = { VALID_NAME_BOB + PHONE_DESC_BOB + EMAIL_DESC_BOB + ADDRESS_DESC_BOB, // missing name prefix
        NAME_DESC_BOB + VALID_PHONE_BOB + EMAIL_DESC_BOB + ADDRESS_DESC_BOB, // missing phone prefix
        NAME_DESC_BOB + PHONE_DESC_BOB + VALID_EMAIL_BOB + ADDRESS_DESC_BOB, // missing email prefix
        NAME_DESC_BOB + PHONE_DESC_BOB + EMAIL_DESC_BOB + VALID_ADDRESS_BOB, // missing address prefix
        VALID_NAME_BOB + VALID_PHONE_BOB + VALID_EMAIL_BOB + VALID_ADDRESS_BOB }) // all prefixes missing
public void parse_compulsoryFieldMissing_failure(String userInput) {
    assertParseFailure(parser, userInput, String.format(MESSAGE_INVALID_COMMAND_FORMAT, AddCommand.MESSAGE_USAGE));
}
```

**Comment by Rinder5** [comment]
Parameterized testing exists in JUnit4, using a runner:
https://github.com/junit-team/junit4/wiki/Parameterized-tests

We can change our tests, even without JUnit5.

**Comment by damithc** [comment]
Let's not bring in new concepts if we can help it. Weak students can tolerate verbosity but cannot survive concept overload. We can of course add a comment to mention how to reduce verbosity and leave it to students to change if they want.

**Comment by Zhiyuan-Amos** [comment]
@damithc should we close this issue, or should we update a test to become a parameterized test as a sample for students to follow if they want to?

**Comment by damithc** [comment]
> It seems like leaving a sample in a random part of the code base is not visible enough for the students. As such, I think that we can just close this issue.

Agreed.
