### ISSUE TITLE
Ui: order tag labels in person cards lexicographically

### ISSUE THREAD

**Issue by eugenepeh** [se-edu/addressbook-level4#808]
Labels in person cards ui are unorganized. This makes it difficult for users to search for a specific tag visually.

We can organize them in alphabetical/lexicographical order (e.g. using `String::compareTo` as a comparator). This will make it easier for users to find a specific tag if they are properly ordered.

[Description updated by @damithc based on comments below]

**Comment by yamgent** [comment]
Organize in alphabetical/lexicographical order (e.g. using `String::compareTo` as a comparator). This will make it easier for users to find a specific tag if they are properly ordered.

**Comment by damithc** [comment]
yes, that can be useful. Not sure if we should leave it for students to do though. On a related note, should we have such issues in this issue tracker and use a special label to indicate they are left as potential enhancements for future forks?

**Comment by yamgent** [comment]
> On a related note, should we have such issues in this issue tracker and use a special label to indicate they are left as potential enhancements for future forks?

Could be useful to leave it here, otherwise someone in the future might open the same issue again and try to get it merged by mistake. However, I feel that mixing suggestions for students, together with actual issues, makes the tracker unwieldly.

Maybe there could be a separate document, specially for students, that documents all these suggestions? That way, when we open a new issue, we will also specifically check against that document to verify that it is not something that we intentionally left it for the students.

**Comment by eugenepeh** [comment]
> Organize in what way?

Oh, forgot to mentioned :P was thinking either lexicographically or oldest to latest. 

>Not sure if we should leave it for students to do though.

I think students might not want to tackle such issues because it is not a "brilliant" or "flashy" feature, unless we offer it to them as suggestion. 

> Maybe there could be a separate document, specially for students, that documents all these suggestions? That way, when we open a new issue, we will also specifically check against that document to verify that it is not something that we intentionally left it for the students.

I think we can leave it as issues here and label them potential issues/features for future fork and also for our own reference. That way we can hand pick these issues as suggestions for future batch, and leave it as suggestions in the semester organization itself. Stronger teams might even come to se-edu to pick out issues to do :P

**Comment by yamgent** [comment]
> I think we can leave it as issues here and label them potential issues/features for future fork and also for our own reference.

Sounds good. Maybe we can use `c.EnhancementForStudents` as a label?

**Comment by damithc** [comment]
Yes, we can apply a special label and close the issue. The list of such issues can easily be found using a label filter and even can be linked from elsewhere. That's less work than maintaining another document. :-p

**Comment by damithc** [comment]
I'm going to use `s.DeferredToFutureForks` to indicate features that are deferred to a future forks. They can be found [here](https://github.com/se-edu/addressbook-level4/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3As.DeferredToFutureForks+)
