### ISSUE TITLE
Implement undo function for each command

### ISSUE THREAD

**Issue by eugenepeh** [se-edu/addressbook-level4#809]
Undo resets the AddressBook to previous state.

This implies that we save the state of the AddressBook each time we execute an undoable command. As the number of persons expands and more undo-able commands being execute, it leads to huge memory usage and slows down the system. 

Let's replace reset data to previous AddressBook by implementing undo function for each command.

Discussed in #792

**Comment by damithc** [comment]
Need to confirm if there is really a memory leak. When we were doing HubTurbo we found that JavaFX has a habit of increasing memory usage if there is enough memory to use (i.e., delay garbage collection as long as possible). This results in seeing a huge memory usage but it seems it is done in order to improve performance (i.e., to avoid the cost of frequent garbage collection). i.e., it is actually harmless as the memory will be released if needed by other apps. At least that's what those students who investigated the issue told me.

**Comment by eugenepeh** [comment]
I think for this issue, irregardless of memory leak, saving an inverse command should be better than saving the entire AddressBook state as each state contains all the Persons, Tags and etc.

**Comment by pyokagan** [comment]
We recently made `Person` immutable and removed Person's copy constructor in #765 . In other words, Person fields will not be duplicated unless they are modified. This should help alleviate memory use somewhat.

**Comment by eugenepeh** [comment]
>We recently made Person immutable and removed Person's copy constructor in #765 . In other words, Person fields will not be duplicated unless they are modified. This should help alleviate memory use somewhat.

I agree, assume that there isn't memory leak anywhere. At the same time, I think personally feel that copying the entire state is not a good practice as this may introduce dangling pointers, and also slows down garbage collection.

Additionally, from current undo and AddressBook implementation, it doesn't seems its a fast process either as the AddressBook grows bigger.

https://github.com/se-edu/addressbook-level4/blob/e7f43d3f05fd8e336c4387e059af92ed50a70512/src/main/java/seedu/address/logic/commands/UndoableCommand.java#L32-L36

https://github.com/se-edu/addressbook-level4/blob/e7f43d3f05fd8e336c4387e059af92ed50a70512/src/main/java/seedu/address/model/AddressBook.java#L47-L50

https://github.com/se-edu/addressbook-level4/blob/e7f43d3f05fd8e336c4387e059af92ed50a70512/src/main/java/seedu/address/model/AddressBook.java#L65-L77

**Comment by damithc** [comment]
You are right, saving the entire model after each command is indeed not a scalable solution. But I don't mind doing it that way if the alternative is more complex, in the interest of keeping the code simple. In that case we can simply document this shortcoming and possible alternatives. In fact optimizing AB for users that need to work with a large contact list (e.g., HR admin, telemarketers, etc.) is one of the enhancements students can do as their project. Those students can implement the more complex but more efficient solution.

On the other hand if there is a more efficient and elegant solution that is also not much more complicated than the current one, I'm all for it. Also, if the current way causes some bugs, we have no choice but to replace it.

**Comment by pyokagan** [comment]
Performance-wise, the only bottleneck left is all the O(n^2) stuff going on in `UniquePersonList`. Applying a patch like this will make undo/redo fly even with 9999 persons:

```diff
diff --git a/src/main/java/seedu/address/model/person/UniquePersonList.java b/src/main/java/seedu/address/model/person/UniquePersonList.java
index 7def02f..8d8a47d 100644
--- a/src/main/java/seedu/address/model/person/UniquePersonList.java
+++ b/src/main/java/seedu/address/model/person/UniquePersonList.java
@@ -3,8 +3,10 @@ package seedu.address.model.person;
 import static java.util.Objects.requireNonNull;
 import static seedu.address.commons.util.CollectionUtil.requireAllNonNull;
 
+import java.util.HashSet;
 import java.util.Iterator;
 import java.util.List;
+import java.util.Set;
 
 import javafx.collections.FXCollections;
 import javafx.collections.ObservableList;
@@ -25,13 +27,14 @@ import seedu.address.model.person.exceptions.PersonNotFoundException;
 public class UniquePersonList implements Iterable<Person> {
 
     private final ObservableList<Person> internalList = FXCollections.observableArrayList();
+    private final Set<Person> internalSet = new HashSet<>();
 
     /**
      * Returns true if the list contains an equivalent person as the given argument.
      */
     public boolean contains(Person toCheck) {
         requireNonNull(toCheck);
-        return internalList.stream().anyMatch(toCheck::isSamePerson);
+        return internalSet.contains(toCheck);
     }
 
     /**
@@ -45,6 +48,7 @@ public class UniquePersonList implements Iterable<Person> {
             throw new DuplicatePersonException();
         }
         internalList.add(toAdd);
+        internalSet.add(toAdd);
     }
 
     /**
@@ -67,6 +71,8 @@ public class UniquePersonList implements Iterable<Person> {
         }
 
         internalList.set(index, editedPerson);
+        internalSet.remove(target);
+        internalSet.add(editedPerson);
     }
 
     /**
@@ -79,10 +85,13 @@ public class UniquePersonList implements Iterable<Person> {
         if (!internalList.remove(toRemove)) {
             throw new PersonNotFoundException();
         }
+        internalSet.remove(toRemove);
     }
 
     public void setPersons(UniquePersonList replacement) {
         this.internalList.setAll(replacement.internalList);
+        this.internalSet.clear();
+        this.internalSet.addAll(replacement.internalSet);
     }
 
     public void setPersons(List<Person> persons) throws DuplicatePersonException {
@@ -92,6 +101,8 @@ public class UniquePersonList implements Iterable<Person> {
         }
 
         this.internalList.setAll(persons);
+        this.internalSet.clear();
+        this.internalSet.addAll(persons);
     }
 
     /**
@@ -122,12 +133,12 @@ public class UniquePersonList implements Iterable<Person> {
      * Returns true if {@code persons} contains only unique persons.
      */
     private boolean personsAreUnique(List<Person> persons) {
-        for (int i = 0; i < persons.size() - 1; i++) {
-            for (int j = i + 1; j < persons.size(); j++) {
-                if (persons.get(i).isSamePerson(persons.get(j))) {
-                    return false;
-                }
+        Set<Person> tmp = new HashSet<>();
+        for (Person person : persons) {
+            if (tmp.contains(person)) {
+                return false;
             }
+            tmp.add(person);
         }
         return true;
     }
```

**Comment by pyokagan** [comment]
Wrt memory: don't see how that is a problem really -- just cap the number of undo/redo entries. (Even the alternative optimized method will also need to do that rather than letting it grow without bound)

Really, I still don't think it is worth the implementation effort. #861 probably took at least 60 reviewer+author hours combined.

Anyway, I already put in a special request through #861 to make it easy for students to implement the optimized version if they wish. This issue can be `s.DeferredToFutureForks`.

**Comment by pyokagan** [comment]
Closing as `s.DeferredToFutureForks`. As mentioned in https://github.com/se-edu/addressbook-level4/issues/809#issuecomment-403075621, the current main performance bottleneck is the O(n^2) implementation in `UniquePersonList`. Memory usage can be improved, but is not worth the extra code given that AB-4 only needs to support up to 1000 entries.
