### ISSUE TITLE
Make PersonCard and ResultDisplay similar to other UiParts

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#82]
Is it possible to make these two similar to how we create other UiParts?

**Comment by Zhiyuan-Amos** [comment]
Hi prof, possible to give further explanations?

**Comment by damithc** [comment]
At the time this issue was created, the two parts followed a different structure than the other UI parts (I can't remember how exactly though).  If there are no such differences now, can close.  For example, see if the ResultDisplay and CommandBox are done similarly because they are peer components in the GUI.

**Comment by Zhiyuan-Amos** [comment]
invalidated by #423
