### ISSUE TITLE
typicalPersonsAddressBook.xml: remove @code tag for header comment

### ISSUE THREAD

**Issue by yamidark** [se-edu/addressbook-level4#822]
`@code` tag is used for javadocs and not .xml files.

**Comment by yamgent** [comment]
For clarification, the offending line is this:

https://github.com/se-edu/addressbook-level4/blob/95611eb437b8e84e51f4b0555fa483fbad05a16b/src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml#L3
