### ISSUE TITLE
Verify the content of dummy page loaded in BrowserPanel

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level4#823]
When a contact is selected in the PersonListPanel, a dummy "search" page
now shows up on the BrowserPanel. Tests that checks the BrowserPanel
currently verifies only the URL loaded by the BrowserPanel.

As we now control the dummy page, we could strengthen such tests, by
ensuring that the content of the dummy page is as what we expected.

Let's enhance the tests involving BrowserPanel to ensure that the
content of the dummy page actually loads properly.

**Comment by pyokagan** [comment]
I don't think this would be very useful, since students won't be using the dummy search page in their actual product.

The method that is used to verify the content in the dummy search page would also very likely fail in the more dynamic websites that students use.

**Comment by damithc** [comment]
I'm Ok to close this issue.
