### ISSUE TITLE
Test data: `isPrivate` XML attribute is unused

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level4#824]
Our xml test data contains the `isPrivate` XML attribute, which is inherited from the lower levels of addressbook.

https://github.com/se-edu/addressbook-level4/blob/6951a73c502185c54370c16fde85605743899d55/src/test/data/XmlUtilTest/validAddressBook.xml#L5-L7

It doesn't seem to be used in level 4, we should either implement something useful with it, or remove such unused attributes.

**Comment by pyokagan** [comment]
Fixed in https://github.com/se-edu/addressbook-level4/commit/77ef0a2efd44f9cc6ad59795208f3713a07e3a83
