### ISSUE TITLE
RedoCommandTest: remove bypassing of encapsulation

### ISSUE THREAD

**Issue by yamidark** [se-edu/addressbook-level4#828]
https://github.com/se-edu/addressbook-level4/blob/d840c89cb12c18786d9c12ebadbb3e1a52aa0441/src/test/java/seedu/address/logic/commands/RedoCommandTest.java#L32-L37

After #792, `UndoableCommand#redo()` depends on the `UndoableCommand` calling `Command#execute()` first in order to preprocess the command.

`RedoCommandTest` calls the methods `UndoableCommand#preprocessUndoableCommand` for each `DeleteCommand` directly as this is a unit test, and to prevent long lines of preparation code. However, it is not desirable to call `UndoableCommand#preprocessUndoableCommand` outside of `UndoableCommand` since it is a `protected` method, as doing so bypasses the encapsulation.

**Comment by Zhiyuan-Amos** [comment]
@yamidark if you're intd to resolve this issue, do take a look at #670. ^^

**Comment by yamidark** [comment]
@Zhiyuan-Amos Will take a look at it.
