### ISSUE TITLE
TestUtil: update methods to use filtered list

### ISSUE THREAD

**Issue by yamidark** [se-edu/addressbook-level4#829]
https://github.com/se-edu/addressbook-level4/blob/ad1931da167821973ba96acef54eb1fef8c8abe5/src/test/java/seedu/address/testutil/TestUtil.java#L37-L39

https://github.com/se-edu/addressbook-level4/blob/ad1931da167821973ba96acef54eb1fef8c8abe5/src/test/java/seedu/address/testutil/TestUtil.java#L44-L46

https://github.com/se-edu/addressbook-level4/blob/ad1931da167821973ba96acef54eb1fef8c8abe5/src/test/java/seedu/address/testutil/TestUtil.java#L51-L53

Methods in `TestUtil` such as `getMidIndex(Model)`, `getLastIndex(Model)`
and `getPerson(Model, Index)` returns the index and person based on the
entire address book instead of the model's filtered list.

When tests require a filtered list, we will get the incorrect person
or index upon calling these methods in TestUtil.

Let's update these methods in `TestUtil` to return values from the
model's filtered list.

**Comment by yamgent** [comment]
> Shall we also add more test cases to DeleteCommandSystemTest and SelectCommandSystemTest to use filtered person list?

These cases should have already been tested on the integration and unit level. In the system level, focus should be on ensuring that the components interact with each other properly for certain scenarios (e.g. when list is filtered, the UI renders properly and the model doesn't give a wrong list). Hence, it might not be necessary to add more test cases (IIRC, Prof frowns upon having such test cases, unless they add value to testing the interactions).

However, in `SelectCommandSystemTest`, there seem to be places where we can take advantage of the methods:

https://github.com/se-edu/addressbook-level4/blob/c9b222cb2870b23760122cadb82248769442fa96/src/test/java/systemtests/SelectCommandSystemTest.java#L46-L49
