### ISSUE TITLE
UniquePersonList#remove(Person): update return value

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [se-edu/addressbook-level4#830]
`remove(Person)` returns true if the person passed into this method can be found in the internal list, and false otherwise. `remove(Person)` also throws `PersonNotFoundException` if the person cannot be found in the internal list.

There's no need for this method to return a boolean value to signal whether the person can be found in the internal list, since this method already throws `PersonNotFoundException` when the person cannot be found.

Let's update this method's return value to `void`.

**Comment by nicholaschuayunzhi** [comment]
Hi @Zhiyuan-Amos I would like to work on this but i do have some queries.

Should the same idea apply to `AddressBook#removePerson(Person)` ? https://github.com/se-edu/addressbook-level4/blob/529d75ffaf497d650fc077251bb3eb0fe976c5e8/src/main/java/seedu/address/model/AddressBook.java#L138-L149

Additionally where do i find information for commit message/branch naming convention. Thank you!

**Comment by yamgent** [comment]
Hi @nicholaschuayunzhi, thanks for your interest in addressbook!

> Should the same idea apply to `AddressBook#removePerson(Person)` ?

Yes, the same idea applies. It would be extremely helpful for us if you fix that as well. :)

> Additionally where do i find information for commit message/branch naming convention. Thank you!

The convention can be found [here](https://github.com/oss-generic/process/blob/master/docs/FormatsAndConventions.adoc#formats-and-conventions).
Additionally, the process for submitting a PR can be found [here](https://github.com/oss-generic/process/blob/master/docs/QuestionsIssuesPrs.adoc#submitting-a-pr), which you will find it useful as well.

**Comment by Zhiyuan-Amos** [comment]
@yamgent so hardcore sia, he wanted me to reply, not you :( 

HAHA kidding, thanks @yamgent 😂
