### ISSUE TITLE
SystemTests: Refactor PersonBuilder to use TypicalPersons as arguments

### ISSUE THREAD

**Issue by vivekscl** [se-edu/addressbook-level4#855]
In many cases, to create a person for testing, the constants from `CommandTestUtil` is used with `PersonBuilder` like so: 
```java
        toAdd = new PersonBuilder().withName(VALID_NAME_AMY).withPhone(VALID_PHONE_BOB).withEmail(VALID_EMAIL_AMY)
                .withAddress(VALID_ADDRESS_AMY).withTags(VALID_TAG_FRIEND).build();
```

This way of creating persons is long-winded and is restricted to only two Persons (Amy and Bob). 

Let's refactor these usages to a more concise form like so:
```java
toAdd = new PersonBuilder(AMY).withPhone(VALID_PHONE_BOB).build()
```

**Comment by yamidark** [comment]
I believe this can be done already using the other `PersonBuilder` constructor:
https://github.com/se-edu/addressbook-level4/blob/2f4405c75cd21111952565a9706a9793b475c41e/src/test/java/seedu/address/testutil/PersonBuilder.java#L42-L48
