### ISSUE TITLE
Increase encapsulation of UniquePersonList

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level4#87]
It's a bit odd to have a `getInternalList()` method. On the surface it looks like a violation of encapsulation. To be investigated further.

**Comment by YijinL** [comment]
It's there because javafx methods require `ObservableList`s, we can make ``UniquePersonList` itself implement that interface but that will be a lot of additional boilerplate code for the class. Thoughts?

**Comment by damithc** [comment]
I see. Perhaps rename the method to avoid the word `internal`? `getObservableList()`?

**Comment by YijinL** [comment]
`.asObservableList` and probably we can use the `UnmodifiableObservableList` as the return type
