### ISSUE TITLE
Feedback from CS2103/T AY1718S2 students

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#883]
To: CS2103/T AY1718S2 students

Congratulations on completing your project! Now that you have spent a few weeks working with AddressBook-Level4, we would like to know your thoughts on the code base.

Specifically,

* Were there any issues with the code that made it difficult for you to implement your features?
    * I found it hard to write UI tests because...
* Were there any design decisions that you found puzzling?
    * e.g. "Why was `Person` suddenly made immutable in Level4? I want `ReadOnlyPerson` back!"
    * e.g. "Why is there [`Config`](https://github.com/se-edu/addressbook-level4/blob/master/src/main/java/seedu/address/commons/core/Config.java) when there is already [`UserPrefs`](https://github.com/se-edu/addressbook-level4/blob/master/src/main/java/seedu/address/model/UserPrefs.java)?"
* Did you encounter any bugs with the code provided to you?
* Do you have any enhancement ideas?
    * e.g. "The parser should tell us about all arguments that were unsuccessfully parsed, not only the first one."
    * (Note: it is *very* unlikely we will be adding any new features)
* Others, if applicable.

Not quite applicable:

* Feedback on lectures/tutorials/pace etc. of CS2103 (we are not the teaching team)
    * Give your feedback via the NUS Student Feedback Exercise instead.

This is a chance for you to get your burning questions answered, and to contribute towards improving later iterations of the AddressBook-Level4 code.

Note: we are not part of the CS2103 teaching team, and so any feedback given by you will have **no effect on your grade**. As such, we would appreciate your most candid feedback :smile: 

Alternatively, you may contact us or chat privately with us on [Gitter](https://gitter.im/se-edu/Lobby).

(PS: We are always in need of help! Do consider [contributing](https://github.com/se-edu/se-edu.github.io#contributing)!)

**Comment by pyokagan** [comment]
Seems like we are perfect :-D Time to pack up, everything is done here :-P

@damithc You can reuse the issue as a template for subsequent semesters if needed.

**Comment by damithc** [comment]
> @damithc You can reuse the issue as a template for subsequent semesters if needed.

Will do.
