### ISSUE TITLE
Cannot run tests through gradle on JDK 10

### ISSUE THREAD

**Issue by dhack8** [se-edu/addressbook-level4#884]
Hi there,

I have setup the project in the steps laid out in the setup section of the documentation but I get errors when trying to run the tests through gradle with the `gradlew clean allTests` or `gradlew clean headless allTests` commands.

I can run the app and the tests (all passing) just fine through IntelliJ.

I am on Windows 10, Using Java JDK 10.0.1 and the most recent version of IntelliJ.

Here is the log file.
[log.txt](https://github.com/se-edu/addressbook-level4/files/1966123/log.txt)

I have done a bit of searching on the internet but can't seem to find anything helpful.

Any help would be greatly appreciated :)

**Comment by pyokagan** [comment]
> Using Java JDK 10.0.1 

I can reproduce on my system (Linux).

@damithc I guess this will need to be solved before the next semester.

@dhack8 Maybe try using JDK 9?

**Comment by pyokagan** [comment]
> I guess this will need to be solved before the next semester.

Since students will likely be installing the latest JDK again.

**Comment by pyokagan** [comment]
Seems like we need to force gradle to use the latest version of jacoco (with JDK 10 support)

```diff
diff --git a/build.gradle b/build.gradle
index 75a518e..cf8f8e9 100644
--- a/build.gradle
+++ b/build.gradle
@@ -114,6 +114,10 @@ task(allTests)
 allTests.dependsOn guiTests
 allTests.dependsOn nonGuiTests
 
+jacoco {
+    toolVersion = '0.8.1'
+}
+
 test {
     systemProperty 'testfx.setup.timeout', '60000'
 
```

**Comment by damithc** [comment]
> @damithc I guess this will need to be solved before the next semester.

Yup.

**Comment by dhack8** [comment]
@pyokagan I tried JDK 9 and still have the issue
I have also tried both IntelliJ 2017 and 2018

**Comment by pyokagan** [comment]
@dhack8 

I just tried it with JDK 9 and I have no issues.

Perhaps you have both JDK 9 and JDK 10 installed on your computer, and so it is still using JDK 10? You will need to set the `JAVA_HOME` environment variable to explicitly point to the location of your JDK 9 installation. (e.g. https://www.wikihow.com/Set-Java-Home )

**Comment by dhack8** [comment]
@pyokagan Yup it was that, forgot about JAVA_HOME
