### ISSUE TITLE
Discontinued support for JDK 9

### ISSUE THREAD

**Issue by hidingmode** [se-edu/addressbook-level4#909]
It is no longer available for download from https://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html

Since the project is dependent on JDK 9, I think it is better if it is upgraded to using JDK 10.

**Comment by hidingmode** [comment]
Oh, alright.

**Comment by damithc** [comment]
@hidingmode JDK 9 is still available from the [Java Archive](http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase9-3934878.html)

**Comment by hidingmode** [comment]
Good to know that JDK 9 is still available for download! I think Prof @damithc should inform other students to download from there if you haven't.

As I was not aware that JDK 9 can still be downloaded, I was using JDK 10 and 8. **Even though the project can be run using JDK 10, the editor kept showing errors on javafx packages.** So I just try testing with different combinations of project SDK and language levels, hoping that the editor can work and the project can run.

Not sure if this will be of any use but I am documenting down my findings here on what happened when I use JDK 10 and 8 for the project.

In IntelliJ, there are 2 settings:
![image](https://user-images.githubusercontent.com/7817101/45226358-32909a00-b2f1-11e8-8ca2-d3fac2858b61.png)
- Project SDK (which is the JDK version it uses to compile the project)
- Project language level (which configures the code assistance for the editor)

**For each of SDK 8 and 10, I used each of language levels 8, 9, 10, to check if the editor can resolve javafx codes, and to run all tests.**

## SDK 10 and language levels 10 and 9
Editor cannot resolve javafx stuff
![image](https://user-images.githubusercontent.com/7817101/45227303-d4fd4d00-b2f2-11e8-9139-be59cf7555d7.png)
1 failed test: `seedu.address.ui.HelpWindowTest.focus_helpWindowNotFocused_focused` with the following error message
![image](https://user-images.githubusercontent.com/7817101/45226684-20632b80-b2f2-11e8-8441-4856069ff281.png)

## SDK 10 and language level 8
Editor can resolve javafx stuff
Compile error
![image](https://user-images.githubusercontent.com/7817101/45227151-a7b09f00-b2f2-11e8-84b8-cfb584b22d0e.png)

## SDK 8 and language levels 10 and 9
Editor can resolve javafx stuff
Compile error
![image](https://user-images.githubusercontent.com/7817101/45227457-1ee63300-b2f3-11e8-9915-67e7dc0ef3ec.png)
Same error for language level 10, just that instead of 9, it is 10.

## SDK 8 and language level 8
Editor can resolve javafx stuff
29 failed tests (all tests in the following classes):
```
seedu.address.ui.BrowserPanelTest
seedu.address.ui.CommandBoxTest
seedu.address.ui.HelpWindowTest
seedu.address.ui.MainWindowCloseTest
seedu.address.ui.PersonCardTest
seedu.address.ui.PersonListPanelTest
seedu.address.ui.ResultDisplayTest
seedu.address.ui.StatusBarFooterTest
systemtests.AddCommandSystemTest
systemtests.ClearCommandSysterTest
systemtests.DeleteCommandSystemTest
systemtests.EditCommandSystemTest
systemtests.ErrorDialogGuiTest
systemtests.FindCommandSystemTest
systemtests.HelpCommandSystemTest
systemtests.SampleDataTest
systemtests.SelectCommandSystemTest
```

**Comment by pyokagan** [comment]
@hidingmode 
> SDK 10 and language levels 10 and 9
> Editor cannot resolve javafx stuff

Yeah, this is a new "feature" which IntelliJ introduced in their latest version (2018.2). Its safe to <kbd>Alt+Enter</kbd> and follow what IntelliJ asks you to do.

@yamidark was kind enough to update the documentation for AB-3 in https://github.com/se-edu/addressbook-level3/commit/d50ff008c66a70dd26e01a3ae2efe5a91849de6f . Unfortunately, we don't have a way (yet) of applying PRs between address book levels, so someone will have to update the documentation in AB-4 as well.

> 1 failed test: seedu.address.ui.HelpWindowTest.focus_helpWindowNotFocused_focused with the following error message

Oh whoops. I think I broke it in https://github.com/se-edu/addressbook-level4/commit/a42ededd0a4f986397105ea5a3e835ac13c3777c . Fix coming up.

> SDK 8 and language levels 10 and 9
> Editor can resolve javafx stuff
> Compile error

Yeah it'll only work with JDK 9 and up.

**Comment by hidingmode** [comment]
@damithc 
> JDK 9 is still available from the Java Archive

FYI, downloading JDK 9 through the java archive site requires oracle login but I guess nothing we can do about that.
