### ISSUE TITLE
Remove EventBus

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#936]
Problems with EventBus:

* It is global -- state leaks can easily occur (and *have* occurred) in tests

* Events are useful for modeling unpredictable inputs in time (e.g. key presses, mouse movements). However, keyboard/mouse input is already handled by the JavaFX framework. Most of the code using EventBus can be rewritten into regular structured code.

* It's an additional thing to learn for students.

* Code using the EventBus can't be re-used in lower AB levels.

* `EventsCollectorRule` is blocking migration to JUnit5.

## Migration Strategy

Overall strategy:

* Use regular code where possible.

* Use the observer pattern (i.e. JavaFX's observable value system) for the rest.

### Saving

**Current implementation**: When the model's address book is modified in any way, `ModelManager` raises an `AddressBookChangedEvent`. This is handled directly by `StorageManager`, which goes on to save the address book.

**Replacement**: `LogicManager#execute(...)` calls `Storage#saveAddressBook(...)`. Simple and direct.

### Data saving exception

**Current implementation**: If an `IOException` occurs while saving the address book, `StorageManager` raises a `DataSavingExceptionEvent`, which is handled by `UiManager` which then shows an error dialog. No error recovery is performed.

**Replacement**: When `LogicManager` calls `Storage#saveAddressBook(...)`, it can simply bubble any exceptions up to the UI via `CommandException`. Simple and direct.

Bonus: Proper error-recovery is now also possible and can be done idiomatically.

### Selecting a person in the person list

**Current implementation**: `SelectCommand` raises a `JumpToListRequestEvent`, which is handled by `PersonListPanel`.

**Replacement**: Introduce an observable `selectedPersonIndex` field to the model, and `PersonListPanel` two-way-binds its selected index to that field.

Side-benefit: Opens up the possibility of more user-friendly commands in the future that do not need to take an explicit index; can simply use `selectedPersonIndex`, since it is now explicitly modeled.

### Navigating to the person page in the browser panel

**Current implementation**: `PersonListPanel` attaches a selection change event handler to its `personListView`. When the selection changes, a `PersonPanelSelectionChangedEvent` is raised, which is handled by `BrowserPanel`.

**Replacement**: `BrowserPanel` simply watches for changes to the `selectedPersonIndex` field in the model. 

### Displaying command results in UI

**Current implementation**: `CommandBox` raises a `NewResultAvailableEvent`, which is handled by `ResultDisplay`.

**Replacement**: `MainWindow` maintains a `commandResult` observable property, which `CommandBox` and `ResultDisplay` binds to.

### Showing help

**Current implementation**: Command that wants to show help will raise a `ShowHelpRequestEvent`.

**Replacement**: Command that wants to show help returns a `CommandResult` with the `showHelp` flag set.

Side-benefit: Easier to test, just do assertEquals on the returned CommandResult.

### Exiting the application

**Current implementation**: `ExitCommand` raises a `ExitAppRequestEvent`, which is handled by `MainApp` (which then calls `Platform.exit()`/`System.exit()` -- the nuclear button).

**Replacement**: Commands that want to exit returns a `CommandResult` with the `exit` flag set.

Side-benefit: Easier to test, just do assertEquals on the returned CommandResult.

Side note: No nuclear buttons are actually needed; JavaFX will automatically terminate by default once all windows are hidden. Just hide the `MainWindow` and `HelpWindow` when such a `CommandResult` is received.

### "Last updated" status in status bar

**Current implementation**: StatusBarFooter listens for `AddressBookChangedEvent`, and updates its last updated status whenever it is raised.

**Replacement**: StatusBarFooter watches for changes to `AddressBook#getPersonList()`, and updates its last updated status whenever it changes.

### Developer Guide

Following Developer Guide sections will be impacted:

* [Event-driven nature of the design](https://github.com/se-edu/addressbook-level4/blob/master/docs/DeveloperGuide.adoc#events-driven-nature-of-the-design)
    * Replacement: Design is not event driven anymore. (Only the UI/JavaFX layer is). Will be replaced with "How the architecture components work together", featuring a high-level sequence diagram showing how Ui/Logic/Model/Storage work together to execute `delete 1`.

![newdiagram](https://user-images.githubusercontent.com/109479/49599705-9e4fd500-f9bc-11e8-9828-9b02ef7077e3.png)

* "Suggested Programming Tasks to get Started"
   * Didn't expect so many tasks for the UI :-O I'd suggest some of them be removed for now.

**Comment by Zhiyuan-Amos** [comment]
I raised #834 previously which also attempts to remove `EventBus` by using `delegation` / `callback`. I guess we'll not be doing that anymore, and we'll be using `Observable` instead?

**Comment by damithc** [comment]
No objections from me, and thanks for taking this on @pyokagan

**Comment by yamgent** [comment]
> "Suggested Programming Tasks to get Started"
> * Didn't expect so many tasks for the UI :-O I'd suggest some of them be removed for now.

Will take a look at all the exercises again when the codebase stabilizes. Some of the questions/answers could have gotten outdated again by the recent changes in codebase anyway.
