### ISSUE TITLE
Website Maintenance and Development

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level4#954]
This is a slightly more open-ended project that may interest students who are interested in web development.

**Background**:

@damithc is planning to move the [oss-generic/process](https://github.com/oss-generic/process) repo into the se-edu org. Since we will need to add a navigation item for it on the SE-EDU navigation bar (which requires us to update the website template on all repos), this would be a good time to do some website development and maintenance.

**Problem Statement**:

The main task is to **assist in migration of oss-generic/process over to the se-edu org**. In addition, **the repo will need to be converted to use markbind** (Rationale: we have two templates, one for asciidoctor and one for markbind. Asciidoctor by itself itsn't designed to be a website generator, and we don't want to introduce and maintain templates for a new website generator)

At the same time, we can do enhancements to the website template, to be proposed by the student. Please discuss them in this issue.

(Note that website enhancements are purely optional (we don't really *need* them), and are allowed for this project so that students can have some fun or practice web development if they want to. Besides, we need to update the templates for all our repos anyway.)

Some examples of possible enhancements:

* Make our navigation bar "stick" to the top of the screen while scrolling. (Somewhat tricky to design, since we have *two* navigation bars)
* Make our asciidoctor and MarkBind templates look consistent, taking the best parts of their designs.

Mentor: @pyokagan

**Comment by pyokagan** [comment]
>     * Make our asciidoctor and MarkBind templates look consistent, taking the best parts of their designs.

Actually, in light of the learning resources page becoming inconsistent with the website design since MarkBind broke the template (again), it might be a good idea to change the asciidoctor template so that it looks the same as MarkBind template.

<sup>(To be clear: I don't really have any strong views on how the website should look like. I just want it to be *consistent* and linked together into a single cohesive site T_T )</sup>

**Comment by damithc** [comment]
Let's wait a bit to see if we can get MarkBind to play nice with non-MarkBind TopNav's. If that works, we can stick with the previous look and feel we had at https://github.com/se-edu/learningresources/commit/d83822e65c93c0a0a48f76fa146ef20cd2a9ab1b

**Comment by pyokagan** [comment]
Closing this because I don't think MarkBind is ready for such a migration yet. We can explore it again later.
