### ISSUE TITLE
Usage of ExpectedException thrown = ExpectedException.none()

### ISSUE THREAD

**Issue by sijie123** [se-edu/addressbook-level4#958]
While I was upgrading from JUnit 4 to JUnit 5 (#874),
I realised that some classes had this odd rule
https://github.com/se-edu/addressbook-level4/blob/3605c4d463019994025093eb09b3dac2ed860172/src/test/java/seedu/address/commons/core/ConfigTest.java#L12-L13

I found it odd that we a clause to say "expect no exceptions", because that's the purpose of a test...
If a test succeeds, then there were no exceptions; If the test fails, we will see that an exception was thrown.

I'm guessing that this exists because some tests will overwrite this `thrown`. For example:
https://github.com/se-edu/addressbook-level4/blob/3605c4d463019994025093eb09b3dac2ed860172/src/test/java/seedu/address/commons/core/VersionTest.java#L11-L12
https://github.com/se-edu/addressbook-level4/blob/3605c4d463019994025093eb09b3dac2ed860172/src/test/java/seedu/address/commons/core/VersionTest.java#L21-L25

In that case, as I migrate to JUnit 5, should we use the assertThrows() syntax instead of the blanket rule (extensions, as it's called in JUnit 5)?

**Comment by Zhiyuan-Amos** [comment]
> I found it odd that we a clause to say "expect no exceptions", because that's the purpose of a test... If a test succeeds, then there were no exceptions; If the test fails, we will see that an exception was thrown.

Yup you are right 👍 

> I'm guessing that this exists because some tests will overwrite this `thrown`.

Yup! I think `ConfigTest` is the odd one out. 

> as I migrate to JUnit 5, should we use the assertThrows() syntax instead of the blanket rule

As per [documentation](https://junit.org/junit5/docs/current/user-guide/), `@Rule and @ClassRule no longer exist`; they have been superseded. So, replacing with `assertThrows` is sensible; it makes it clear which tests we are expecting to have exceptions (so we don't experience the `ConfigTest` scenario).

If you could look up on `extensions vs assertThrows` that'll be good too, cos the natural thing to ask is: If we were using rules previously and they are superseded with extensions, then why aren't we using extensions instead.

**Comment by pyokagan** [comment]
`assertThrows()` is hands down better because you can use it multiple times in the same test. We also need to be very careful when using `thrown.expect()` -- it should only be used right at the *end* of the test (with the statement being tested), otherwise the test may still pass if an unrelated statement happened to throw the same exception.

Anyway, closing this issue since it seems to be a question that has been answered.
