### ISSUE TITLE
docs/diagrams: `.pptx` for `DeletePersonSdForLogic.png` is missing

### ISSUE THREAD

**Issue by Creastery** [se-edu/addressbook-level4#977]
The corresponding `.pptx` for [docs/images/DeletePersonSdForLogic.png](https://github.com/se-edu/addressbook-level4/blob/3a8f0b7d5c762d47a83bd5339fbc5c9af9a36a0f/docs/images/DeletePersonSdForLogic.png) diagram is missing.

It appears that the `.pptx` for `docs/images/DeletePersonSdForLogic.png` diagram is [docs/diagrams/LogicComponentSequenceDiagram.pptx](https://github.com/se-edu/addressbook-level4/blob/cbc6571757d250295849622286c1d8bf7cf8d621/docs/diagrams/LogicComponentSequenceDiagram.pptx) from cbc6571 in #546.

However, the `LogicComponentSequenceDiagram.pptx` file was replaced in the migration away from EventsCenter [89ec0382bcd3fe34edf1205ff02248ae5f954074] to include: [docs/images/SDforDeletePerson.png](https://github.com/se-edu/addressbook-level4/blob/89ec0382bcd3fe34edf1205ff02248ae5f954074/docs/images/SDforDeletePerson.png)

Since both `docs/images/SDforDeletePerson.png` and `docs/images/DeletePersonSdForLogic.png` are currently included in the [DeveloperGuide](https://github.com/se-edu/addressbook-level4/blob/3a8f0b7d5c762d47a83bd5339fbc5c9af9a36a0f/docs/DeveloperGuide.adoc), I suggest that we:
* retain the existing `LogicComponentSequenceDiagram.pptx` from 89ec038
(to allow updating of `SDforDeletePerson.png`)
* restore the original `LogicComponentSequenceDiagram.pptx` from cbc6571
(to allow updating of `DeletePersonSdForLogic.png`)

**Comment by pyokagan** [comment]
@Creastery 
> However, the `LogicComponentSequenceDiagram.pptx` file was replaced in the migration away from EventsCenter [[89ec038](https://github.com/se-edu/addressbook-level4/commit/89ec0382bcd3fe34edf1205ff02248ae5f954074)] to include: [docs/images/SDforDeletePerson.png](https://github.com/se-edu/addressbook-level4/blob/89ec0382bcd3fe34edf1205ff02248ae5f954074/docs/images/SDforDeletePerson.png)

Oh no. Looks like I replaced the wrong pptx file. The pptx file that was supposed to be replaced was `HighLevelSequenceDiagrams.pptx`, not `LogicComponentSequenceDiagram.pptx`.

Will open a PR to fix this.
