### ISSUE TITLE
JUnit: TestFX has insufficient permissions to control cursor and keyboard in macOS Mojave

### ISSUE THREAD

**Issue by Creastery** [se-edu/addressbook-level4#979]
It appears that TestFX has insufficient permissions to control cursor or keyboard in macOS Mojave.

The code causing this issue is at:
https://github.com/se-edu/addressbook-level4/blob/5509159e39b3939d64ddffb36970e27b692135ce/src/test/java/guitests/guihandles/CommandBoxHandle.java#L25-L34

Because macOS Mojave introduced a few privacy enhancements, programs are unable to simulate keyboard and mouse movements, unless Accessibility permission is granted in `System Settings > Settings and Privacy`. Refer to TestFX/TestFX#641 for more details.

Although TestFX is unable to move the cursor to the `TextField`, it is still able to enter the command successfully, as the `guiRobot` sets the text of the `TextField` directly.
```java
guiRobot.interact(() -> getRootNode().setText(command));
```

However, `CommandBoxHandle#run(...)` relies on having an ENTER key pressed on the TextField to trigger the `CommandBox.fxml#TextField`'s `onAction` handler - `CommandBox#handleCommandEntered()`:
https://github.com/se-edu/addressbook-level4/blob/5509159e39b3939d64ddffb36970e27b692135ce/src/main/java/seedu/address/ui/CommandBox.java#L95-L109

Because TestFX is unable to simulate an ENTER key press without Accessibility permissions, the result is that:
(1) `CommandBox#handleCommandEntered()` is not called, and 
(2) `TextField`'s text is not cleared

Hence, the following unit tests will fail:
```
src/test/java/systemtests/EditCommandSystemTest.java 
src/test/java/systemtests/FindCommandSystemTest.java
src/test/java/systemtests/AddCommandSystemTest.java
src/test/java/systemtests/HelpCommandSystemTest.java
src/test/java/systemtests/SelectCommandSystemTest.java
src/test/java/systemtests/ClearCommandSystemTest.java
src/test/java/systemtests/DeleteCommandSystemTest.java
```

Perhaps the best solution to fix this issue is to update the documentation to suggest to developers using macOS Mojave to grant Accessibility permission to IntelliJ IDEA in `System Settings > Settings and Privacy`.

Thanks @lycjackie for finding and investigating the bug together! 👍

**Comment by pyokagan** [comment]
@Creastery 
> It appears that TestFX has insufficient permissions to control cursor or keyboard in macOS Mojave.

Did MacOS give you the prompt? (Replace "Steam" with IntelliJ or Terminal/iTerm/etc.)

![steam-accessibility-settings](https://user-images.githubusercontent.com/109479/53491708-043a8d00-3ad2-11e9-84ef-e3e17206ec9d.png)

> Perhaps the best solution to fix this issue is to update the documentation to suggest to developers using macOS Mojave to grant Accessibility permission to IntelliJ IDEA in `System Settings > Settings and Privacy`.

Yes, that'll be good. PRs welcome.

**Comment by Creastery** [comment]
@pyokagan 
> Did MacOS give you the prompt? (Replace "Steam" with IntelliJ or Terminal/iTerm/etc.)
> 
> ![steam-accessibility-settings](https://user-images.githubusercontent.com/109479/53491708-043a8d00-3ad2-11e9-84ef-e3e17206ec9d.png)

Nope, IntelliJ IDEA did not ask for Accessibility permissions even when running the unit tests.

> > Perhaps the best solution to fix this issue is to update the documentation to suggest to developers using macOS Mojave to grant Accessibility permission to IntelliJ IDEA in `System Settings > Settings and Privacy`.
> 
> Yes, that'll be good. PRs welcome.

Sure, will open a PR when I have the time to work on this. 
Is [DeveloperGuide - Section 5.3 Troubleshooting Testing](https://github.com/se-edu/addressbook-level4/blob/master/docs/DeveloperGuide.adoc#53-troubleshooting-testing) the right section to update?

**Comment by pyokagan** [comment]
@Creastery 
> Is [DeveloperGuide - Section 5.3 Troubleshooting Testing](https://github.com/se-edu/addressbook-level4/blob/master/docs/DeveloperGuide.adoc#53-troubleshooting-testing) the right section to update?

That looks like a good place to me, although @damithc may wish to confirm. I didn't really design the documentation structure :stuck_out_tongue:

**Comment by damithc** [comment]
> That looks like a good place to me

Yes, I agree.  👍
